Repository noobaa/noobaa-operator, pull requests merged in 2021-09, with the labels that each got.

#736 Adding the ability to change/add labels in service monitor
  deploy/crds/noobaa.io_noobaas_crd.yaml
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/deploy.go
  pkg/system/phase4_configuring.go
Labels: size/L

#737 Cleaning the logs from mongodb errors when we have postgres.
  pkg/system/phase2_creating.go
Labels: size/XS

#719 Custom annotations and labels for noobaa core and db
  deploy/crds/noobaa.io_noobaas_crd.yaml
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
Labels: size/L

#738 Update dependencies according to OCS-operator
  deploy/crds/noobaa.io_backingstores_crd.yaml
  deploy/crds/noobaa.io_noobaas_crd.yaml
  go.mod
  go.sum
  pkg/bundle/deploy.go
  pkg/olm/olm.go
  pkg/system/phase4_configuring.go
  pkg/system/reconciler.go
  pkg/util/util.go
Labels: size/XL

#721 Adding DB dump functionality to the CLI
  pkg/cli/cli.go
  pkg/dbdump/dbdump.go
  pkg/diagnose/diagnose.go
  test/cli/test_cli_flow.sh
  test/cli/test_cli_functions.sh
Labels: size/L
