Repository noobaa/noobaa-operator, pull requests merged in 2021-12, with the labels that each got.

#810 Websocket client - improve server disconnect detection
  pkg/nb/rpc_ws.go
Labels: size/M

#812 Updating prometheus-rules for odf
  deploy/internal/prometheus-rules.yaml
  pkg/bundle/deploy.go
Labels: size/XS

#774 Extend support bucket qouta
  deploy/crds/noobaa.io_bucketclasses_crd.yaml
  pkg/apis/noobaa/v1alpha1/bucketclass_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bucket/bucket.go
  pkg/bucketclass/bucketclass.go
  pkg/bucketclass/reconciler.go
  pkg/bucketclass/validation.go
  pkg/bundle/deploy.go
  pkg/nb/types.go
  pkg/obc/obc.go
  pkg/obc/provisioner.go
  pkg/obc/validation.go
  pkg/util/util.go
Labels: size/L

#813 [Backport to 5.9] set EnableHTTPSTrafficOnly on create storage account
  pkg/system/azure_utils.go
Labels: size/XS

#815 Moved configmap annotation to change the deployment strategies of the endpoint from recreate to ramped
  deploy/internal/deployment-endpoint.yaml
  deploy/internal/statefulset-core.yaml
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
Labels: size/M

#806 Add admission validation webhook server
  .github/workflows/run_admission_test.yml
  Makefile
  deploy/internal/admission-webhook.yaml
  pkg/admission/server.go
  pkg/admission/test/integ/admission_integ_test.go
  pkg/admission/test/integ/admission_suite_integ_test.go
  pkg/admission/test/unit/admission_suite_unit_test.go
  pkg/admission/test/unit/admission_unit_test.go
  pkg/admission/validate_backingstore.go
  pkg/admission/validate_namespacestore.go
  pkg/admission/validator.go
  pkg/backingstore/reconciler.go
  pkg/bundle/deploy.go
  pkg/olm/olm.go
  pkg/operator/manager.go
  pkg/operator/operator.go
  pkg/util/util.go
Labels: size/XXL

#794 Adding `fsGroupChangePolicy` and `seLinuxOptions` to `securityContext`
  deploy/internal/deployment-endpoint.yaml
  deploy/scc_endpoint.yaml
  pkg/bundle/deploy.go
Labels: size/S

#820 Bump version to 5.10
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#823 updated ContainerImageTag for 5.9.0 release
  pkg/options/options.go
Labels: size/XS

#816 Fix password logged in clear text
  pkg/nb/types.go
  pkg/system/phase4_configuring.go
Labels: size/S

#824 updated default core image to master-20211222
  pkg/options/options.go
Labels: size/XS

#821 Add Bucketclass admission validations
  deploy/internal/admission-webhook.yaml
  pkg/admission/test/integ/admission_integ_test.go
  pkg/admission/test/unit/admission_unit_test.go
  pkg/admission/validate_bucketclass.go
  pkg/admission/validate_namespacestore.go
  pkg/admission/validator.go
  pkg/bucketclass/validation.go
  pkg/bundle/deploy.go
  pkg/util/util.go
Labels: size/L

#819 IBM Key Protect KMS module
  .github/workflows/run_kms_ibm_kp_test.yml
  .travis/install-ibm-kp-kms-noobaa.sh
  Makefile
  go.mod
  go.sum
  pkg/system/phase2_creating.go
  pkg/system/reconciler.go
  pkg/util/kms/kms.go
  pkg/util/kms/kms_ibm_kp.go
  pkg/util/kms/kms_ibm_kp_k8s_secret.go
  pkg/util/kms/kms_k8s.go
  pkg/util/kms/kms_vault.go
  pkg/util/kms/test/dev/kms_dev_suite_test.go
  pkg/util/kms/test/dev/kms_dev_test.go
  pkg/util/kms/test/ibm-kp/kms_ibm_kp_suite_test.go
  pkg/util/kms/test/ibm-kp/kms_ibm_kp_test.go
  pkg/util/kms/test/tls-sa/kms_tls_sa_suite_test.go
  pkg/util/kms/test/tls-sa/kms_tls_sa_test.go
  pkg/util/kms/test/tls-token/kms_tls_token_suite_test.go
  pkg/util/kms/test/tls-token/kms_tls_token_test.go
  pkg/util/util.go
Labels: size/XL
