Repository noobaa/noobaa-operator, pull requests merged in 2021-08, with the labels that each got.

#697 Support building noobaa-operator on ARM64 and other architectures
  Makefile
  build/install-operator-sdk.sh
Labels: enhancement, NEW CONTRIBUTOR !!!, WIP PR, size/XS

#722 Add documentation to replication policy usage in bucketclass and OBC
  doc/bucket-class-crd.md
  doc/obc-provisioner.md
Labels: size/M

#723 [Backport to 5.7] if dbtype is not provided try to infer it from the db image name
  pkg/system/phase2_creating.go
  pkg/system/system.go
Labels: size/M

#725 Add disable SSL to RGW connection
  pkg/system/phase4_configuring.go
Labels: size/S

#724 GH Action Add push to quay repo
  .github/workflows/manual-build.yml
Labels: size/S

#717 bump lib bucket provisioner version and add update callback in provisioner
  go.mod
  go.sum
  pkg/nb/api.go
  pkg/nb/types.go
  pkg/obc/obc.go
  pkg/obc/provisioner.go
  test/cli/test_cli_flow.sh
  test/cli/test_cli_functions.sh
Labels: size/L

#726 [backport to 5.7] postgres performance improvements
  deploy/internal/configmap-postgres-db.yaml
  deploy/internal/statefulset-postgres-db.yaml
  pkg/bundle/deploy.go
Labels: size/M

#727 updated build action to build and push bundle image to quay
  .github/workflows/manual-build.yml
  Makefile
  build/bundle/Dockerfile
  build/bundle/annotations.yaml
Labels: size/M

#728 Add insecure transportation for creation bucket on RGW
  pkg/system/phase4_configuring.go
Labels: size/XS

#729 fixed manual-build.yml OPERATOR_BUNDLE_TAGS
  .github/workflows/manual-build.yml
Labels: size/XS

#731 Changing the flow of the tests
  pkg/bucket/bucket.go
  pkg/bucketclass/bucketclass.go
  test/cli/test_cli_flow.sh
  test/cli/test_cli_functions.sh
Labels: size/M

#730 Adding noobaa-odf.rules
  deploy/internal/prometheus-rules.yaml
  pkg/bundle/deploy.go
Labels: size/M

#732 Update prom rules in operator
  deploy/internal/prometheus-rules.yaml
  pkg/bundle/deploy.go
Labels: size/M

#733 Adding timeout to RGW S3 https client
  pkg/system/phase4_configuring.go
Labels: size/XS
