Repository noobaa/noobaa-operator, pull requests merged in 2021-11, with the labels that each got.

#751 Allow definition of pv-pool backing store agent resources requests/limits
  pkg/backingstore/backingstore.go
  pkg/backingstore/reconciler.go
  test/cli/test_cli_flow.sh
  test/cli/test_cli_functions.sh
Labels: size/L

#788 Fix CLI install - DB init container
  deploy/scc_endpoint.yaml
  pkg/bundle/deploy.go
Labels: size/XS

#784 Remove the prints of S3 credentials from NooBaa create backingstore and namespacestore
  pkg/backingstore/backingstore.go
  pkg/namespacestore/namespacestore.go
Labels: size/XS

#792 [backport to 5.8] removed tiering creation for namespace buckets
  pkg/obc/provisioner.go
  pkg/system/phase4_configuring.go
Labels: size/S

#795 Revert "Merge pull request #792 from dannyzaken/danny-backport-5.8"
  pkg/obc/provisioner.go
  pkg/system/phase4_configuring.go
Labels: size/S

#789 Add webhook configuration to csv
  deploy/internal/admission-webhook.yaml
  pkg/bundle/deploy.go
  pkg/olm/olm.go
Labels: size/M

#798 added toleration node.ocs.openshift.io/storage to noobaa-operator deployment
  pkg/olm/olm.go
Labels: size/XS

#799 [backport to 5.9] added toleration node.ocs.openshift.io/storage to noobaa-operator deployment
  pkg/olm/olm.go
Labels: size/XS

#801 fixed default backingstore creation in azure
  pkg/system/phase4_configuring.go
Labels: size/S

#797 Use Service Account for KMS authentication
  .github/workflows/run_kms_dev_test.yml
  .github/workflows/run_kms_tls_sa_test.yml
  .github/workflows/run_kms_tls_token_test.yml
  .travis/deploy-validate-vault.sh
  .travis/generate-tls-config.sh
  .travis/install-dev-kms-noobaa.sh
  .travis/install-dev-vault.sh
  .travis/install-tls-kms-noobaa.sh
  Makefile
  go.mod
  go.sum
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
  pkg/system/reconciler.go
  pkg/util/kms.go
  pkg/util/kms_k8s.go
  pkg/util/kms_vault.go
  pkg/util/test/dev/kms_dev_suite_test.go
  pkg/util/test/dev/kms_dev_test.go
  pkg/util/test/tls-sa/kms_tls_sa_suite_test.go
  pkg/util/test/tls-sa/kms_tls_sa_test.go
  pkg/util/test/tls-token/kms_tls_token_suite_test.go
  pkg/util/test/tls-token/kms_tls_token_test.go
  pkg/util/util.go
Labels: size/XXL

#771 ignore namespace not found in remove-namespace.sh script
  build/remove-namespace.sh
Labels: size/XS

#800 Add admission webhook cli deployment
  deploy/internal/admission-webhook.yaml
  deploy/internal/service_admission_webhook.yaml
  pkg/bundle/deploy.go
  pkg/operator/operator.go
  pkg/options/options.go
  test/cli/test_cli_functions.sh
  test/test-olm.sh
Labels: size/L
