Repository noobaa/noobaa-operator, pull requests merged in 2022-11, with the labels that each got.

#993 Adding disconnected annotations to the CSV
  deploy/olm/noobaa-operator.clusterserviceversion.yaml
  pkg/bundle/deploy.go
  pkg/olm/olm.go
Labels: size/XS

#994 [Backport to 5.12] Adding disconnected annotations to the CSV
  deploy/olm/noobaa-operator.clusterserviceversion.yaml
  pkg/bundle/deploy.go
  pkg/olm/olm.go
Labels: size/XS

#992 Handle creating backingstore with the CLI and the "--secret-name" option.
  pkg/backingstore/backingstore.go
  pkg/namespacestore/namespacestore.go
Labels: size/S

#995 [Backport to 5.12] Handle creating backingstore with the CLI and the "--secret-name" option
  pkg/backingstore/backingstore.go
  pkg/namespacestore/namespacestore.go
Labels: size/S

#997 Update in Backing Store CRD Documentation
  doc/backing-store-crd.md
Labels: documentation, size/XS

#996 Map alternate keys value
  pkg/backingstore/reconciler.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: size/M
