Repository noobaa/noobaa-operator, pull requests merged in 2022-04, with the labels that each got.

#898 Bumped the version in golangci-lint.yml to fix the GH Action lint.
  .github/workflows/golangci-lint.yml
Labels: size/XS

#903 Add noobaa admission controller to prevent CR deletion
  deploy/internal/admission-webhook.yaml
  pkg/admission/validate_noobaa.go
  pkg/admission/validator.go
  pkg/bundle/deploy.go
  pkg/install/install.go
  pkg/operator/operator.go
  test/cli/test_cli_flow.sh
  test/cli/test_cli_functions.sh
Labels: size/L

#902 Fixed cli tests not running
  test/cli/test_cli_flow.sh
  test/cli/test_cli_functions.sh
Labels: size/M

#876 bump to Go 1.17, K8s 1.22.2, Rook 1.8.7
  .github/workflows/manual-build.yml
  .github/workflows/run_admission_test.yml
  .github/workflows/run_ci.yml
  .github/workflows/run_hac_test.yml
  .github/workflows/run_kms_dev_test.yml
  .github/workflows/run_kms_ibm_kp_test.yml
  .github/workflows/run_kms_tls_sa_test.yml
  .github/workflows/run_kms_tls_token_test.yml
  .github/workflows/testing.yml
  deploy/crds/noobaa.io_noobaas_crd.yaml
  go.mod
  go.sum
  pkg/bundle/deploy.go
Labels: size/M

#907 create a pv-pool default backing store in azure gov platforms
  pkg/system/phase2_creating.go
  pkg/util/util.go
Labels: size/S

#908 [backport to 5.10] create a pv-pool default backing store in azure gov platforms
  .github/workflows/golangci-lint.yml
  pkg/system/phase2_creating.go
  pkg/util/util.go
Labels: size/S

#910 [backport to 5.8] create a pv-pool default backing store in azure gov platforms
  .github/workflows/golangci-lint.yml
  pkg/system/phase2_creating.go
  pkg/system/reconciler.go
  pkg/util/util.go
Labels: size/M
