Repository noobaa/noobaa-operator, pull requests merged in 2022-05, with the labels that each got.

#905 Add Noobaa CR cleanup policy
  deploy/cluster_role.yaml
  deploy/crds/noobaa.io_noobaas_crd.yaml
  pkg/admission/validate_noobaa.go
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/bundle/deploy.go
  pkg/install/install.go
  pkg/operator/operator.go
  pkg/system/phase4_configuring.go
  pkg/system/system.go
  pkg/util/util.go
Labels: size/L

#912 [5.10] bumped version to 5.10.1
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#913 Preventing the cli from searching for identical secrets for pvpool
  pkg/backingstore/backingstore.go
  pkg/namespacestore/namespacestore.go
Labels: size/S

#915 Backport to 5.11
  deploy/cluster_role.yaml
  deploy/crds/noobaa.io_noobaas_crd.yaml
  pkg/admission/validate_noobaa.go
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/backingstore/backingstore.go
  pkg/bundle/deploy.go
  pkg/install/install.go
  pkg/namespacestore/namespacestore.go
  pkg/operator/operator.go
  pkg/system/phase4_configuring.go
  pkg/system/system.go
  pkg/util/util.go
Labels: size/L

#917 [5.10] updated core image to 5.10.1
  pkg/options/options.go
Labels: size/XS

#901 Log based replication params change
  pkg/nb/types.go
  pkg/obc/provisioner.go
  pkg/options/options.go
  pkg/util/util.go
  test/cli/test_cli_functions.sh
Labels: size/M

#914 Adding namespace to secretRef from the backingstore or namespacestore when it is missing
  pkg/backingstore/reconciler.go
  pkg/util/util.go
Labels: size/M

#911 Remove UI
  deploy/crds/noobaa.io_noobaas_crd.yaml
  deploy/internal/text/system_status_readme_ready.tmpl
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/bundle/deploy.go
  pkg/cli/cli.go
  pkg/system/cmd_ui.go
  pkg/system/system.go
  test/cli/test_cli_functions.sh
Labels: size/L

#921 Backport to 5.11
  README.md
  pkg/backingstore/reconciler.go
  pkg/bundle/deploy.go
  pkg/util/util.go
  version/version.go
Labels: size/M

#920 Fix searching noobaa webhook by name
  deploy/cluster_role.yaml
  pkg/bundle/deploy.go
  pkg/system/phase4_configuring.go
Labels: size/M

#922 [backport to 5.11] fix searching noobaa webhook by name
  deploy/cluster_role.yaml
  pkg/bundle/deploy.go
  pkg/system/phase4_configuring.go
Labels: size/M

#919 Fix map secret to store
  pkg/backingstore/backingstore.go
  pkg/namespacestore/namespacestore.go
Labels: size/S

#926 Create service account token if it is missing
  .travis/deploy-validate-vault.sh
Labels: size/M

#924 Bump version to 5.12
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#925 Fixing LC_COLLATE - operator side
  deploy/internal/statefulset-postgres-db.yaml
  pkg/bundle/deploy.go
Labels: size/S

#927 Backport to 5.11
  .travis/deploy-validate-vault.sh
  deploy/internal/statefulset-postgres-db.yaml
  pkg/backingstore/backingstore.go
  pkg/bundle/deploy.go
  pkg/namespacestore/namespacestore.go
Labels: size/M

#743 Refactor SCC/RBAC
  deploy/cluster_role.yaml
  deploy/internal/statefulset-db.yaml
  deploy/internal/statefulset-postgres-db.yaml
  deploy/role.yaml
  deploy/role_binding_db.yaml
  deploy/role_db.yaml
  deploy/scc_db.yaml
  deploy/scc_endpoint.yaml
  deploy/service_account_db.yaml
  pkg/bundle/deploy.go
  pkg/olm/olm.go
  pkg/operator/operator.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
Labels: size/L

#929 Add webhook validation on noobaa deletion
  pkg/admission/test/unit/admission_unit_test.go
  pkg/admission/validate_noobaa.go
  pkg/install/install.go
  pkg/system/phase4_configuring.go
  pkg/system/system.go
  pkg/util/util.go
  pkg/validations/noobaa_validation.go
  test/cli/test_cli_functions.sh
Labels: size/L

#931 [Backport to 5.11] Remove UI
  deploy/crds/noobaa.io_noobaas_crd.yaml
  deploy/internal/text/system_status_readme_ready.tmpl
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/bundle/deploy.go
  pkg/cli/cli.go
  pkg/system/cmd_ui.go
  pkg/system/system.go
  test/cli/test_cli_functions.sh
Labels: size/L
