Repository noobaa/noobaa-operator, pull requests merged in 2022-10, with the labels that each got.

#989 [Backport to 5.12] Add create Namespace AWSSTSS3 to the cli
  deploy/internal/deployment-endpoint.yaml
  pkg/admission/test/integ/admission_integ_test.go
  pkg/admission/test/unit/admission_unit_test.go
  pkg/backingstore/reconciler.go
  pkg/bundle/deploy.go
  pkg/namespacestore/namespacestore.go
  pkg/namespacestore/reconciler.go
  pkg/util/util.go
  pkg/validations/namespacestore_validations.go
Labels: size/L

#990 [Backport to 5.12] Supporting warn level in operator
  pkg/bucket/bucket.go
  pkg/bucketclass/bucketclass.go
  pkg/bundler/bundler.go
  pkg/cli/cli.go
  pkg/operator/manager.go
  pkg/system/phase2_creating.go
  pkg/system/reconciler.go
  pkg/util/util.go
Labels: size/M

#991 own OB\OBC CRDs when building bundle image
  .github/workflows/manual-build.yml
Labels: size/XS
