Repository noobaa/noobaa-operator, pull requests merged in 2022-01, with the labels that each got.

#830 Changing default CPU request/limit to 999m
  deploy/internal/deployment-endpoint.yaml
  deploy/internal/statefulset-core.yaml
  pkg/bundle/deploy.go
Labels: size/S

#831 updated dependency to latest lib-bucket-provisioner
  go.mod
  go.sum
Labels: size/XS

#832 Backport to 5.9 - NS FS Fixes only
  deploy/internal/deployment-endpoint.yaml
  deploy/internal/statefulset-core.yaml
  deploy/scc_endpoint.yaml
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
  version/version.go
Labels: size/L

#825 Refactor Backingstore and Namespacestore validations
  pkg/admission/test/integ/admission_integ_test.go
  pkg/admission/test/unit/admission_unit_test.go
  pkg/admission/validate_backingstore.go
  pkg/admission/validate_bucketclass.go
  pkg/admission/validate_namespacestore.go
  pkg/admission/validator.go
  pkg/backingstore/backingstore.go
  pkg/backingstore/reconciler.go
  pkg/backingstore/validation.go
  pkg/bucketclass/reconciler.go
  pkg/bucketclass/validation.go
  pkg/namespacestore/reconciler.go
  pkg/namespacestore/validation.go
  pkg/namespacestore/validation_test.go
Labels: size/XXL

#804 Add Regenerate S3 Credentials to the CLI
  pkg/nb/api.go
  pkg/nb/types.go
  pkg/noobaaaccount/noobaaaccount.go
  test/cli/test_cli_functions.sh
Labels: size/L

#833 Update diagnostics to support both kubectl and oc
  pkg/dbdump/dbdump.go
  pkg/diagnose/diagnose.go
  pkg/util/util.go
Labels: size/M

#834 IBM Key Protect KMS module - Secret Storage
  .github/workflows/run_kms_ibm_kp_test.yml
  .travis/install-ibm-kp-kms-noobaa.sh
  go.mod
  go.sum
  pkg/system/phase2_creating.go
  pkg/util/kms/kms.go
  pkg/util/kms/kms_ibm_kp.go
  pkg/util/kms/kms_ibm_kp_k8s_secret.go
  pkg/util/kms/kms_ibm_kp_storage.go
  pkg/util/kms/kms_k8s.go
  pkg/util/kms/kms_vault.go
  pkg/util/kms/test/ibm-kp/kms_ibm_kp_suite_test.go
  pkg/util/kms/test/ibm-kp/kms_ibm_kp_test.go
Labels: size/XL

#826 Support AWS STS in Noobaa
  deploy/crds/noobaa.io_backingstores_crd.yaml
  deploy/crds/noobaa.io_namespacestores_crd.yaml
  deploy/crds/noobaa.io_noobaas_crd.yaml
  deploy/internal/statefulset-core.yaml
  deploy/operator.yaml
  pkg/apis/noobaa/v1alpha1/backingstore_types.go
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/backingstore/backingstore.go
  pkg/backingstore/reconciler.go
  pkg/backingstore/validation.go
  pkg/bundle/deploy.go
  pkg/namespacestore/validation.go
  pkg/nb/types.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
  pkg/system/reconciler.go
  pkg/system/system.go
  pkg/util/util.go
Labels: size/XL

#835 Separate resource validations to a different package
  pkg/admission/test/unit/admission_unit_test.go
  pkg/admission/validate_backingstore.go
  pkg/admission/validate_bucketclass.go
  pkg/admission/validate_namespacestore.go
  pkg/backingstore/backingstore.go
  pkg/backingstore/reconciler.go
  pkg/bucketclass/bucketclass.go
  pkg/bucketclass/reconciler.go
  pkg/namespacestore/namespacestore.go
  pkg/namespacestore/reconciler.go
  pkg/namespacestore/validation_test.go
  pkg/validations/backingstore_validations.go
  pkg/validations/bucketclass_validation.go
  pkg/validations/namespacestore_validations.go
Labels: size/L

#836 KMS: Rename conf key IBM_KP_INSTANCE_ID -> IBM_KP_SERVICE_INSTANCE_ID
  .github/workflows/run_kms_ibm_kp_test.yml
  pkg/util/kms/kms_ibm_kp_storage.go
Labels: size/XS

#828 STS service and route addition
  deploy/crds/noobaa.io_noobaas_crd.yaml
  deploy/internal/deployment-endpoint.yaml
  deploy/internal/route-sts.yaml
  deploy/internal/service-sts.yaml
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/deploy.go
  pkg/options/options.go
  pkg/system/phase2_creating.go
  pkg/system/phase3_connecting.go
  pkg/system/reconciler.go
  pkg/system/system.go
Labels: size/L

#808 Add reset password to the account menu in the CLI
  pkg/nb/api.go
  pkg/nb/types.go
  pkg/noobaaaccount/noobaaaccount.go
  test/cli/test_cli_functions.sh
Labels: size/L

#827 Add noobaa-odf-ui service account's role rules
  deploy/role_ui.yaml
  deploy/service_account_ui.yaml
  pkg/bundle/deploy.go
  pkg/olm/olm.go
  pkg/operator/operator.go
Labels: size/M

#838 Backport to 5.10
  .github/workflows/run_kms_ibm_kp_test.yml
  pkg/admission/test/unit/admission_unit_test.go
  pkg/admission/validate_backingstore.go
  pkg/admission/validate_bucketclass.go
  pkg/admission/validate_namespacestore.go
  pkg/backingstore/backingstore.go
  pkg/backingstore/reconciler.go
  pkg/bucketclass/bucketclass.go
  pkg/bucketclass/reconciler.go
  pkg/namespacestore/namespacestore.go
  pkg/namespacestore/reconciler.go
  pkg/namespacestore/validation_test.go
  pkg/nb/api.go
  pkg/nb/types.go
  pkg/noobaaaccount/noobaaaccount.go
  pkg/util/kms/kms_ibm_kp_storage.go
  pkg/validations/backingstore_validations.go
  pkg/validations/bucketclass_validation.go
  pkg/validations/namespacestore_validations.go
  test/cli/test_cli_functions.sh
Labels: size/L

#839 fixing getAvailableKubeCli
  pkg/util/util.go
Labels: size/XS

#840 Backport to 5.10
  deploy/role_ui.yaml
  deploy/service_account_ui.yaml
  pkg/bundle/deploy.go
  pkg/olm/olm.go
  pkg/operator/operator.go
  pkg/util/util.go
Labels: size/M

#837 Fix r.OBC nil pointer dereference
  pkg/obc/provisioner.go
  test/cli/test_cli_flow.sh
  test/cli/test_cli_functions.sh
Labels: size/S
