Repository noobaa/noobaa-operator, pull requests merged in 2022-03, with the labels that each got.

#863 Backport to 5.10
  deploy/internal/configmap-postgres-db.yaml
  pkg/bundle/deploy.go
Labels: size/XS

#861 Adding webhook to noobaaaccounts - nsfs config only
  deploy/internal/admission-webhook.yaml
  pkg/admission/validate_noobaaaccount.go
  pkg/admission/validator.go
  pkg/bundle/deploy.go
  pkg/validations/noobaaaccount_validation.go
Labels: size/L

#865 [Backport to 5.10] Add nsfs_account_config to noobaaaccount CRD, Add CLI flags and webhooks
  deploy/crds/noobaa.io_noobaaaccounts_crd.yaml
  deploy/internal/admission-webhook.yaml
  pkg/admission/validate_noobaaaccount.go
  pkg/admission/validator.go
  pkg/apis/noobaa/v1alpha1/noobaaaccount_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/deploy.go
  pkg/nb/types.go
  pkg/noobaaaccount/noobaaaccount.go
  pkg/noobaaaccount/reconciler.go
  pkg/util/util.go
  pkg/validations/noobaaaccount_validation.go
Labels: size/L

#850 Fixed Tech Debt for AWS STS support
  pkg/admission/test/integ/admission_integ_test.go
  pkg/admission/test/unit/admission_unit_test.go
  pkg/system/phase1_verifying.go
  pkg/system/phase4_configuring.go
  pkg/system/system.go
  pkg/validations/backingstore_validations.go
Labels: size/L

#867 Add empty target bucket admission validation
  pkg/admission/test/unit/admission_unit_test.go
  pkg/namespacestore/validation_test.go
  pkg/validations/backingstore_validations.go
  pkg/validations/namespacestore_validations.go
Labels: size/L

#868 Backport to 5.10: add empty target bucket admission validation
  pkg/admission/test/unit/admission_unit_test.go
  pkg/namespacestore/validation_test.go
  pkg/validations/backingstore_validations.go
  pkg/validations/namespacestore_validations.go
Labels: size/L

#870 Adding NooBaaAccount admission unit tests
  pkg/admission/test/unit/admission_unit_test.go
Labels: size/L

#864 Fix install-operator-sdk.sh PLATFORM
  build/install-operator-sdk.sh
Labels: size/XS

#873 Divide the config map cli test to reduce CI run time
  .github/workflows/run_ci.yml
  Makefile
  test/cli/test_cli_flow.sh
Labels: size/M

#854 Support PostgresDB config override from NooBaa CR
  deploy/crds/noobaa.io_noobaas_crd.yaml
  doc/noobaa-crd.md
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
  pkg/validations/backingstore_validations.go
  test/cli/test_cli_flow.sh
  test/cli/test_cli_functions.sh
Labels: size/M

#857 Add Regenerate S3 Credentials for OBC to the CLI
  pkg/obc/obc.go
Labels: size/L

#875 [Backport to 5.10] Add Regenerate S3 Credentials for OBC to the CLI
  .github/workflows/run_ci.yml
  Makefile
  build/install-operator-sdk.sh
  pkg/admission/test/unit/admission_unit_test.go
  pkg/obc/obc.go
  test/cli/test_cli_flow.sh
Labels: size/L

#877 Fix noobaaaccount to be able to get also namespacestore as a resource
  pkg/noobaaaccount/noobaaaccount.go
  pkg/noobaaaccount/reconciler.go
  test/cli/test_cli_functions.sh
Labels: size/M

#879 Add insecureEdgeTerminationPolicy to the route-s3.yaml
  deploy/internal/route-s3.yaml
  pkg/bundle/deploy.go
Labels: size/XS

#880 [Backport to 5.10] Fix noobaaaccount to be able to get also namespacestore as a resource
  pkg/noobaaaccount/noobaaaccount.go
  pkg/noobaaaccount/reconciler.go
  test/cli/test_cli_functions.sh
Labels: size/M

#878 create azure StorageAccount with minTLS 1.2
  pkg/system/azure_utils.go
Labels: size/M

#885 Backport to 5.10
  pkg/system/azure_utils.go
Labels: size/M

#882 [backport to 5.9] create azure StorageAccount with minTLS 1.2
  pkg/system/azure_utils.go
Labels: size/M

#886 [5.8 special backport] Allow definition of pv-pool backing store agent resources requests/limits
  pkg/backingstore/backingstore.go
  pkg/backingstore/reconciler.go
  test/cli/test_cli_flow.sh
  test/cli/test_cli_functions.sh
Labels: size/L

#887 Backport to 5.8 special build
  deploy/internal/route-s3.yaml
  pkg/bundle/deploy.go
Labels: size/XS

#888 Backport to 5.8
  pkg/system/azure_utils.go
Labels: size/M

#884 [backport to 5.7] create azure StorageAccount with minTLS 1.2
  pkg/system/azure_utils.go
Labels: size/M

#889 backport to 5.9
  deploy/internal/route-s3.yaml
  pkg/backingstore/backingstore.go
  pkg/backingstore/reconciler.go
  pkg/bundle/deploy.go
  test/cli/test_cli_flow.sh
  test/cli/test_cli_functions.sh
Labels: size/L

#688 Added ability to update BackingStore external connection
  build/gen-odf-package.sh
  go.mod
  pkg/admission/test/integ/admission_integ_test.go
  pkg/backingstore/backingstore.go
  pkg/backingstore/reconciler.go
  pkg/bucketclass/bucketclass.go
  pkg/controller/backingstore/backingstore_controller.go
  pkg/controller/namespacestore/namespacestore_controller.go
  pkg/namespacestore/namespacestore.go
  pkg/namespacestore/reconciler.go
  pkg/nb/api.go
  pkg/nb/types.go
  pkg/util/util.go
  test/cli/resources/empty-secret.yaml
  test/cli/test_cli_flow.sh
  test/cli/test_cli_functions.sh
Labels: size/XXL

#892 [special backport] dummy target for bundle-image
  Makefile
Labels: size/XS

#893 BP to 5.8_special: tryig to fix actions
  .github/workflows/manual-build.yml
  .github/workflows/next-ver-build.yaml
  .github/workflows/run_admission_test.yml
  .github/workflows/run_ci.yml
  .github/workflows/run_hac_test.yml
  .github/workflows/run_kms_dev_test.yml
  .github/workflows/run_kms_ibm_kp_test.yml
  .github/workflows/run_kms_tls_sa_test.yml
  .github/workflows/run_kms_tls_token_test.yml
  .github/workflows/weekly-build.yml
Labels: size/XL

#896 Fix set ownerReference bug in load store secret
  pkg/backingstore/reconciler.go
  pkg/namespacestore/reconciler.go
Labels: size/S
