Repository noobaa/noobaa-operator, pull requests merged in 2022-12, with the labels that each got.

#999 RBAC for endpoint is handled by OLM
  pkg/olm/olm.go
  pkg/operator/operator.go
  pkg/system/phase4_configuring.go
Labels: size/M

#1001 [Backport to 5.12] RBAC for endpoint is handled by OLM
  pkg/olm/olm.go
  pkg/operator/operator.go
  pkg/system/phase4_configuring.go
Labels: size/M

#1000 Bump version to 5.13
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1003 [Backport to 5.11] Handle creating backingstore with the CLI and the "--secret-name" option.
  .github/workflows/golangci-lint.yml
  pkg/admission/validator.go
  pkg/backingstore/backingstore.go
  pkg/bundler/bundler.go
  pkg/namespacestore/namespacestore.go
  pkg/nb/rpc_http.go
  pkg/nb/rpc_ws.go
  pkg/olm/olm.go
  pkg/system/phase4_configuring.go
  pkg/util/kms/kms_vault.go
  pkg/util/util.go
Labels: size/M

#1005 Prompting more readable error when we get CONNECTED_BUCKET_DELETING
  pkg/validations/backingstore_validations.go
Labels: size/XS
