Repository noobaa/noobaa-operator, pull requests merged in 2022-06, with the labels that each got.

#932 Fix check identical secrets
  pkg/backingstore/backingstore.go
  pkg/backingstore/reconciler.go
  pkg/namespacestore/namespacestore.go
  pkg/namespacestore/reconciler.go
  pkg/util/util.go
Labels: size/M

#935 Backport to 5.11: fix identical secrets
  pkg/backingstore/backingstore.go
  pkg/backingstore/reconciler.go
  pkg/namespacestore/namespacestore.go
  pkg/namespacestore/reconciler.go
  pkg/util/util.go
Labels: size/M

#936 [Backport to 5.11] Add webhook validation on noobaa deletion
  pkg/admission/test/unit/admission_unit_test.go
  pkg/admission/validate_noobaa.go
  pkg/install/install.go
  pkg/system/phase4_configuring.go
  pkg/system/system.go
  pkg/util/util.go
  pkg/validations/noobaa_validation.go
  test/cli/test_cli_functions.sh
Labels: size/L

#938 [backport to 5.11] Fix set secret owner reference
  pkg/backingstore/reconciler.go
  pkg/namespacestore/reconciler.go
  pkg/util/util.go
Labels: size/M

#940 Added option to show/hide secrets in status output
  pkg/noobaaaccount/noobaaaccount.go
  pkg/obc/obc.go
  pkg/options/options.go
  pkg/system/system.go
  test/cli/test_cli_functions.sh
Labels: size/L

#943 cli doesn't show error when creating a backingstore that isn't available in the commands
  pkg/backingstore/backingstore.go
Labels: size/S

#945 Backport to 5.10
  deploy/internal/statefulset-postgres-db.yaml
  pkg/bundle/deploy.go
Labels: size/S

#950 Backport to 5.8: Addition of labels to reconcile after upgrade from last version
  pkg/system/phase2_creating.go
Labels: size/XS

#952 Issue: cli doesn't show error when creating a namespacestore that isn't available in the commands
  pkg/namespacestore/namespacestore.go
Labels: size/S

#955 Remove RPC error type check
  pkg/backingstore/reconciler.go
  pkg/namespacestore/reconciler.go
Labels: size/S
