Repository noobaa/noobaa-operator, pull requests merged in 2022-07, with the labels that each got.

#954 [backport to 5.11] throw temporary error when INVALID_SCHEMA_PARAMS returned from CheckE…
  pkg/backingstore/reconciler.go
  pkg/namespacestore/reconciler.go
Labels: size/S

#948 added set-debug-level command to CLI
  pkg/nb/api.go
  pkg/nb/types.go
  pkg/system/system.go
Labels: size/M

#959 doc: correct 404 page not found error
  doc/namespace-store-crd.md
Labels: size/XS

#960 added an option to own OB\OBC in noobaa CSV
  Makefile
  build/gen-odf-package.sh
  pkg/olm/olm.go
Labels: size/M

#962 Fixed issue #961 - require OBC in CSV when csvParams=nil
  pkg/olm/olm.go
Labels: size/XS
