Repository noobaa/noobaa-operator, pull requests merged in 2022-09, with the labels that each got.

#977 Support OCP injected CA
  deploy/internal/configmap-ca-inject.yaml
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
  pkg/system/reconciler.go
Labels: size/M

#978 Add metrics, odf_system_objects_total and odf_system_bucket_count
  deploy/internal/prometheus-rules.yaml
  pkg/bundle/deploy.go
Labels: size/S

#981 changed the way image existence is checked in manual-build workflow
  .github/workflows/manual-build.yml
Labels: size/XS

#982 remove the labels from odf_system object and bucket count
  deploy/internal/prometheus-rules.yaml
  pkg/bundle/deploy.go
Labels: size/S

#956 remove allowed_buckets from noobaa core
  deploy/crds/noobaa.io_noobaaaccounts_crd.yaml
  doc/noobaa-account-crd.md
  pkg/apis/noobaa/v1alpha1/noobaaaccount_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/backingstore/reconciler.go
  pkg/bundle/deploy.go
  pkg/namespacestore/reconciler.go
  pkg/nb/types.go
  pkg/noobaaaccount/noobaaaccount.go
  pkg/noobaaaccount/reconciler.go
  pkg/obc/provisioner.go
  pkg/options/options.go
  test/cli/test_cli_functions.sh
Labels: size/L

#983 Add access mode to namespacestore resource
  deploy/crds/noobaa.io_namespacestores_crd.yaml
  pkg/apis/noobaa/v1alpha1/bucketclass_types.go
  pkg/apis/noobaa/v1alpha1/namespacestore_types.go
  pkg/bucketclass/bucketclass.go
  pkg/bucketclass/reconciler.go
  pkg/bundle/deploy.go
  pkg/namespacestore/namespacestore.go
  pkg/namespacestore/reconciler.go
  pkg/nb/types.go
  pkg/obc/provisioner.go
  pkg/validations/bucketclass_validation.go
Labels: size/L

#985 [backport to 5.11] support OCP injected CA
  deploy/internal/configmap-ca-inject.yaml
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
  pkg/system/reconciler.go
Labels: size/M

#986 [5.11] bumped version to 5.11.2
  pkg/bundle/deploy.go
  version/version.go
Labels: size/XS

#967 [backport to 5.10] Add a procedure to create noobaa service account token if it is missing
  .travis/deploy-validate-vault.sh
Labels: size/M

#988 [Backport to 5.10] support OCP injected CA
  deploy/internal/configmap-ca-inject.yaml
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
  pkg/system/reconciler.go
Labels: size/M

#942 Support STS credentials for Namespace store
  deploy/internal/deployment-endpoint.yaml
  pkg/admission/test/integ/admission_integ_test.go
  pkg/admission/test/unit/admission_unit_test.go
  pkg/backingstore/reconciler.go
  pkg/bundle/deploy.go
  pkg/namespacestore/namespacestore.go
  pkg/namespacestore/reconciler.go
  pkg/util/util.go
  pkg/validations/namespacestore_validations.go
Labels: size/L
