Repository noobaa/noobaa-operator, pull requests merged in 2022-08, with the labels that each got.

#949 Fixed default secret for backingstore
  pkg/backingstore/backingstore.go
  pkg/system/system.go
Labels: size/XS

#941 Add support for controlling LoadBalancer source subnet
  deploy/crds/noobaa.io_noobaas_crd.yaml
  deploy/internal/admission-webhook.yaml
  deploy/internal/service-mgmt.yaml
  pkg/admission/validate_noobaa.go
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/deploy.go
  pkg/options/options.go
  pkg/system/phase2_creating.go
  pkg/system/system.go
  pkg/validations/noobaa_validation.go
  test/cli/test_cli_flow.sh
  test/cli/test_cli_functions.sh
Labels: size/L

#964 KMIP KMS module
  .github/workflows/run_kms_kmip_test.yml
  .travis/install-kmip-kms-noobaa.sh
  Makefile
  go.mod
  go.sum
  pkg/util/kms/kms_kmip.go
  pkg/util/kms/kms_kmip_storage.go
  pkg/util/kms/test/kmip/kms_kmip_suite_test.go
  pkg/util/kms/test/kmip/kms_kmip_test.go
  pkg/util/kms/test/kmip/pykmip/Dockerfile
  pkg/util/kms/test/kmip/pykmip/k8s/pod.yaml
  pkg/util/kms/test/kmip/pykmip/k8s/service.yaml
  pkg/util/kms/test/kmip/pykmip/server.conf
  pkg/util/kms/test/kmip/pykmip/start.sh
Labels: size/XL

#970 cli: Print on newline, if more than one value
  pkg/system/system.go
  pkg/util/util.go
Labels: size/S

#939 Init noobaa services before populating the status
  pkg/system/reconciler.go
  pkg/system/system.go
Labels: size/S

#972 [BACKPORT to 5.10] throw temporary error when INVALID_SCHEMA_PARAMS returned from CheckE…
  pkg/backingstore/reconciler.go
  pkg/namespacestore/reconciler.go
Labels: size/S

#975 Fix AWS STS checkExternalConnection to pass AWSSTSARN
  pkg/backingstore/reconciler.go
  pkg/nb/types.go
Labels: size/XS

#976 [5.10] Update the z version in version.go file from 5.10.1 to 5.10.6
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S
