Repository noobaa/noobaa-operator, pull requests merged in 2022-02, with the labels that each got.

#844 Fix typo in the admission server cert file name
  pkg/admission/server.go
Labels: size/XS

#845 Backport to 5.10: Fix a typo in the admission server cert file
  pkg/admission/server.go
Labels: size/XS

#849 always install operator sdk for x86. no arm build for v0.17.2
  build/install-operator-sdk.sh
Labels: size/XS

#852 Fix minimum volume size validation
  pkg/validations/backingstore_validations.go
Labels: size/XS

#853 Fix noobaa-db-pg-0 Pod stuck CrashLoopBackOff state
  deploy/internal/configmap-postgres-initdb.yaml
  pkg/bundle/deploy.go
Labels: size/S

#856 Backport to 5.10
  deploy/internal/configmap-postgres-initdb.yaml
  pkg/bundle/deploy.go
  pkg/validations/backingstore_validations.go
Labels: size/S

#858 Add nsfs_account_config to noobaaaccount CRD
  deploy/crds/noobaa.io_noobaaaccounts_crd.yaml
  pkg/apis/noobaa/v1alpha1/noobaaaccount_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/deploy.go
  pkg/nb/types.go
  pkg/noobaaaccount/reconciler.go
Labels: size/L

#860 Increase postgres max connections
  deploy/internal/configmap-postgres-db.yaml
  pkg/bundle/deploy.go
Labels: size/XS

#859 Adding CLI flags is for creating nsfs account
  pkg/noobaaaccount/noobaaaccount.go
  pkg/util/util.go
Labels: size/M

#862 Backport to 5.9: Increase postgres max connections
  deploy/internal/configmap-postgres-db.yaml
  pkg/bundle/deploy.go
Labels: size/XS
