Repository noobaa/noobaa-operator, pull requests merged in 2023-05, with the labels that each got.

#1113 CI | Change Deprecating `set-output`
  .github/workflows/manual-build.yml
  .github/workflows/testing.yml
Labels: size/S

#1118 [Backport to 5.10] Update AWS regions
  .github/workflows/golangci-lint.yml
  .github/workflows/run_admission_test.yml
  .github/workflows/run_ci.yml
  .github/workflows/run_hac_test.yml
  .github/workflows/run_kms_dev_test.yml
  .github/workflows/run_kms_ibm_kp_test.yml
  .github/workflows/run_kms_tls_sa_test.yml
  .github/workflows/run_kms_tls_token_test.yml
  .github/workflows/testing.yml
  pkg/util/util.go
Labels: size/M

#1071 Master Root Key rotation for K8S secret backend
  .github/workflows/run_kms_rotate_test.yml
  Makefile
  deploy/crds/noobaa.io_noobaas_crd.yaml
  go.mod
  go.sum
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/deploy.go
  pkg/options/options.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
  pkg/system/reconciler.go
  pkg/util/kms/kms.go
  pkg/util/kms/kms_ibm_kp.go
  pkg/util/kms/kms_k8s.go
  pkg/util/kms/kms_kmip.go
  pkg/util/kms/kms_vault.go
  pkg/util/kms/kms_version.go
  pkg/util/kms/test/ibm-kp/kms_ibm_kp_test.go
  pkg/util/kms/test/rotate/kms_rotate_suite_test.go
  pkg/util/kms/test/rotate/kms_rotate_test.go
Labels: size/XL

#1117 Adding quantity quota alerts
  deploy/internal/prometheus-rules.yaml
  pkg/bundle/deploy.go
Labels: size/M

#1115 ignore ReadSystemInfo persistent error in deletion
  pkg/backingstore/reconciler.go
  pkg/namespacestore/reconciler.go
Labels: size/XS

#1109 Fixing issue with operator log level
  pkg/system/phase2_creating.go
  pkg/system/reconciler.go
Labels: size/S

#1124 [backport to 5.13] Fixing log set location in the operator
  pkg/system/phase2_creating.go
  pkg/system/reconciler.go
Labels: size/S

#1125 Description changed
  deploy/internal/prometheus-rules.yaml
  pkg/bundle/deploy.go
Labels: size/S

#1127 Remove unwanted character "\" from the description
  deploy/internal/prometheus-rules.yaml
  pkg/bundle/deploy.go
Labels: size/S

#1072 Diagnose Resource
  .github/workflows/run_admission_test.yml
  deploy/job_analyze_resource.yml
  pkg/backingstore/backingstore.go
  pkg/bundle/deploy.go
  pkg/cli/cli.go
  pkg/diagnostics/analyze.go
  pkg/diagnostics/collect.go
  pkg/diagnostics/dbdump.go
  pkg/diagnostics/diagnostics.go
  pkg/namespacestore/namespacestore.go
  pkg/util/util.go
  test/cli/test_cli_functions.sh
Labels: size/XL, Depends on PR

#1126 [Backport to 5.13] - Adding quantity quota alerts
  deploy/internal/prometheus-rules.yaml
  pkg/bundle/deploy.go
Labels: size/M

#1130 fixing issue - setting externalDNS without port
  pkg/system/phase3_connecting.go
Labels: size/XS
