Repository noobaa/noobaa-operator, pull requests merged in 2023-12, with the labels that each got.

#1253 Add Default Backingstore for AWS STS with CCO
  deploy/crds/noobaa.io_backingstores.yaml
  deploy/crds/noobaa.io_namespacestores.yaml
  deploy/crds/noobaa.io_noobaas.yaml
  deploy/internal/deployment-endpoint.yaml
  deploy/internal/statefulset-core.yaml
  deploy/operator.yaml
  pkg/apis/noobaa/v1alpha1/backingstore_types.go
  pkg/bundle/deploy.go
  pkg/olm/olm.go
  pkg/operator/operator.go
  pkg/options/options.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
Labels: size/L

#1258 Bump rook to v1.12.6
  go.mod
  go.sum
Labels: size/M

#1260 Bug Fix #1259 | Fix Bug Operator Restart on GCP Cluster
  pkg/system/phase4_configuring.go
Labels: size/XS

#1255 Doc | Update Backingstore Doc Related to AWS STS
  doc/backing-store-crd.md
Labels: size/XS

#1261 [5.13] Bumping rook to v1.11.4 and k8s.io/api to v0.26.4
  deploy/crds/noobaa.io_backingstores_crd.yaml
  deploy/crds/noobaa.io_noobaas_crd.yaml
  go.mod
  go.sum
  pkg/bundle/deploy.go
Labels: size/M

#1263 Added preStop hook to DB statefulset
  pkg/system/phase2_creating.go
Labels: size/XS

#1267 [5.14] Bumping the version from 5.14.1 to 5.14.2
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1268 Replacing github.com/rook/rook with github.com/rook/rook/pkg/apis
  go.mod
  go.sum
Labels: size/L

#1269 [5.14] Bumping the version from 5.14.2 to 5.14.3
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1265 [Backport into 5.14] Bump dependencies
  go.mod
  go.sum
  pkg/system/phase2_creating.go
Labels: size/L

#1272 [5.13] Bump version to 5.13.6
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1270 [Backport to 5.13] Bug Fix BZ 2242414
  pkg/noobaaaccount/noobaaaccount.go
  pkg/obc/obc.go
Labels: size/S

#1273 [5.12] Bump version to 5.12.11
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1244 Doc | Create AWS STS Setup on Minikube Dev Guide
  doc/dev_guide/create_aws_sts_setup_on_minikube.md
Labels: size/L

#1271 [Backport to 5.12] Bug Fix BZ 2242414
  .github/workflows/golangci-lint.yml
  .github/workflows/run_ci.yml
  pkg/noobaaaccount/noobaaaccount.go
  pkg/obc/obc.go
Labels: size/S

#1276 updated golangci-lint to 1.55 + removed depracated flags
  .github/workflows/golangci-lint.yml
Labels: size/XS
