Repository noobaa/noobaa-operator, pull requests merged in 2023-01, with the labels that each got.

#1006 Bumped to GO v1.18 rook v1.10.1 controller-runtime v0.13.1
  .github/workflows/golangci-lint.yml
  .github/workflows/manual-build.yml
  .github/workflows/run_admission_test.yml
  .github/workflows/run_ci.yml
  .github/workflows/run_hac_test.yml
  .github/workflows/run_kms_dev_test.yml
  .github/workflows/run_kms_ibm_kp_test.yml
  .github/workflows/run_kms_kmip_test.yml
  .github/workflows/run_kms_tls_sa_test.yml
  .github/workflows/run_kms_tls_token_test.yml
  .github/workflows/testing.yml
  Makefile
  build/DockerfileDev
  deploy/crds/noobaa.io_backingstores_crd.yaml
  deploy/crds/noobaa.io_bucketclasses_crd.yaml
  deploy/crds/noobaa.io_namespacestores_crd.yaml
  deploy/crds/noobaa.io_noobaaaccounts_crd.yaml
  deploy/crds/noobaa.io_noobaas_crd.yaml
  go.mod
  go.sum
  pkg/bundle/deploy.go
  pkg/util/util.go
Labels: size/XXL

#1008 [Backport to 5.12] Prompting more readable error when we get CONNECTED_BUCKET_DELETING
  pkg/validations/backingstore_validations.go
Labels: size/XS

#1013 Update vault v1.11.2 to v1.12.2
  go.mod
  go.sum
Labels: size/L

#1018 use a specific tag for smallstep/step-ca in kmip test
  .travis/install-kmip-kms-noobaa.sh
Labels: size/XS

#895 Multi Namespace BucketClass
  Makefile
  doc/bucket-class-crd.md
  doc/obc-provisioner.md
  pkg/admission/server.go
  pkg/admission/validate_bucketclass.go
  pkg/admission/validator.go
  pkg/bucketclass/reconciler.go
  pkg/controller/add_bucketclass.go
  pkg/controller/backingstore/backingstore_controller.go
  pkg/controller/bucketclass/bucketclass_controller.go
  pkg/controller/bucketclass/bucketclass_suite_test.go
  pkg/controller/bucketclass/bucketclass_test.go
  pkg/controller/controller.go
  pkg/controller/ha/ha_controller.go
  pkg/controller/namespacestore/namespacestore_controller.go
  pkg/controller/noobaa/noobaa_controller.go
  pkg/obc/obc_suite_test.go
  pkg/obc/obc_test.go
  pkg/obc/provisioner.go
  pkg/operator/manager.go
  pkg/operator/operator.go
  pkg/operator/operator_suite_test.go
  pkg/operator/operator_test.go
  pkg/options/options.go
  pkg/util/predicates.go
  pkg/util/predicates_test.go
  pkg/util/util.go
  pkg/util/util_suite_test.go
  pkg/validations/bucketclass_validation.go
  test/cli/test_cli_flow.sh
  test/cli/test_cli_functions.sh
Labels: size/XL

#1022 Bump consul-template and kubectl
  go.mod
  go.sum
Labels: size/L

#1024 Bumped secrets to avoid CVE
  go.mod
  go.sum
Labels: size/XXL

#1028 [5.8] Update version to 5.8.18
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1027 [5.9] Update version to 5.9.14
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1026 [5.10] Update version to 5.10.10
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1002 Support feature to disable default backingstore
  deploy/crds/noobaa.io_noobaas_crd.yaml
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/bundle/deploy.go
  pkg/options/options.go
  pkg/system/phase1_verifying.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
  pkg/system/system.go
  test/cli/test_cli_flow.sh
  test/cli/test_cli_functions.sh
Labels: size/L

#998 Add workflow for automated NooBaa releases
  .github/workflows/releaser.yaml
  build/Dockerfile
  build/tools/builder-pre.sh
  build/tools/builder.sh
  build/tools/releaser-post.sh
  build/tools/releaser.sh
  build/tools/utils.sh
Labels: size/XL

#1015 Mounting secrets into a file instead of secretKeyRef
  deploy/internal/deployment-endpoint.yaml
  deploy/internal/statefulset-core.yaml
  pkg/bundle/deploy.go
  pkg/options/options.go
  pkg/system/phase4_configuring.go
Labels: size/M

#1032 Adding support for Namespace GoogleCloudStorage
  deploy/crds/noobaa.io_namespacestores_crd.yaml
  doc/namespace-store-crd.md
  pkg/admission/validate_namespacestore.go
  pkg/apis/noobaa/v1alpha1/namespacestore_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/deploy.go
  pkg/namespacestore/namespacestore.go
  pkg/namespacestore/reconciler.go
  pkg/util/util.go
  pkg/validations/namespacestore_validations.go
Labels: size/L

#1021 build: use proper operator-sdk on ARM64
  build/install-operator-sdk.sh
Labels: size/S

#1030 changes to all GitHub workflows - timeout, checkout v3, concurrency, general cleanup
  .github/workflows/golangci-lint.yml
  .github/workflows/manual-build.yml
  .github/workflows/releaser.yaml
  .github/workflows/run_admission_test.yml
  .github/workflows/run_ci.yml
  .github/workflows/run_hac_test.yml
  .github/workflows/run_kms_dev_test.yml
  .github/workflows/run_kms_ibm_kp_test.yml
  .github/workflows/run_kms_kmip_test.yml
  .github/workflows/run_kms_tls_sa_test.yml
  .github/workflows/run_kms_tls_token_test.yml
  .github/workflows/testing.yml
Labels: size/L

#1039 Add the characters EXAMPLE as a prefix in secrets examples
  doc/install-on-minikube-on-ubuntu.md
  doc/obc-provisioner.md
Labels: size/XS
