Repository noobaa/noobaa-operator, pull requests merged in 2023-08, with the labels that each got.

#1181 Create external-postgres.md
  doc/external-postgres.md
Labels: size/M

#1186 [Chore] Update install instructions for NooBaa
  README.md
Labels: size/S

#1183 Remove operator-sdk dependency
  Makefile
  build/Dockerfile
  build/hack/boilerplate.go.txt
  deploy/crds/noobaa.io_backingstores.yaml
  deploy/crds/noobaa.io_bucketclasses.yaml
  deploy/crds/noobaa.io_namespacestores.yaml
  deploy/crds/noobaa.io_noobaaaccounts.yaml
  deploy/crds/noobaa.io_noobaas.yaml
  pkg/apis/noobaa/v1alpha1/backingstore_types.go
  pkg/apis/noobaa/v1alpha1/bucketclass_types.go
  pkg/apis/noobaa/v1alpha1/namespacestore_types.go
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/apis/noobaa/v1alpha1/noobaaaccount_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/deploy.go
  pkg/crd/crd.go
  test/test-olm.sh
Labels: size/XL

#1184 update go version
  .github/workflows/manual-build.yml
  .github/workflows/run_admission_test.yml
  .github/workflows/run_ci.yml
  .github/workflows/run_cosi_test.yaml
  .github/workflows/run_hac_test.yml
  .github/workflows/run_kms_dev_test.yml
  .github/workflows/run_kms_ibm_kp_test.yml
  .github/workflows/run_kms_kmip_test.yml
  .github/workflows/run_kms_rotate_test.yml
  .github/workflows/run_kms_tls_sa_test.yml
  .github/workflows/run_kms_tls_token_test.yml
  .github/workflows/testing.yml
  go.mod
  pkg/cli/cli.go
Labels: size/M

#1192 Correcting misaligned .PHONY in Makefile
  Makefile
Labels: size/XS

#1190 Skip hpav2 resources if metrics type is Resource
  pkg/system/autoscaler.go
Labels: size/XS

#1189 Update AWS Regions
  pkg/util/util.go
Labels: size/XS

#1188 Pass Region Param to External Connection
  pkg/backingstore/reconciler.go
  pkg/namespacestore/reconciler.go
  pkg/nb/types.go
Labels: size/M

#1194 [backport to 5.14] Skip hpav2 resources if metrics type is Resource
  pkg/system/autoscaler.go
Labels: size/XS

#1199 [backport to 5.14] Fix the operator image make target
  Makefile
Labels: size/XS

#1200 CLI | Fix creation and validation of OBC with replication
  pkg/cosi/cosi_bucket_claim.go
  pkg/cosi/provisioner.go
  pkg/cosi/validation.go
  pkg/obc/obc.go
  pkg/obc/provisioner.go
  pkg/obc/validation.go
  pkg/validations/common_bucket_validation_integ_test.go
  pkg/validations/common_bucket_validations.go
Labels: size/M

#1178 [5.13] Bump version to 5.13.1
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1201 [5.13] Bump version to 5.13.2
  .github/workflows/run_admission_test.yml
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1195 Add support for config file
  .gitignore
  go.mod
  go.sum
  pkg/cli/cli.go
  pkg/system/system.go
Labels: size/L

#1203 BugFix - [MCG] RPC method "list_objects" fails with "RPC: object.list…
  pkg/nb/router.go
Labels: size/XS

#1204 [backport to 5.14] Fixed noobaa CLI api calls to object_api
  pkg/nb/router.go
Labels: size/XS

#1202 Pass Region in Analyze Resource
  deploy/job_analyze_resource.yml
  pkg/bundle/deploy.go
  pkg/diagnostics/analyze.go
Labels: size/S

#1205 Bumping rook
  deploy/crds/noobaa.io_backingstores.yaml
  deploy/crds/noobaa.io_noobaas.yaml
  go.mod
  go.sum
  pkg/backingstore/backingstore.go
  pkg/bucketclass/bucketclass.go
  pkg/bundle/deploy.go
  pkg/controller/backingstore/backingstore_controller.go
  pkg/controller/bucketclass/bucketclass_controller.go
  pkg/controller/cephcluster/cephcluster_controller.go
  pkg/controller/ha/ha_controller.go
  pkg/controller/namespacestore/namespacestore_controller.go
  pkg/controller/noobaa/noobaa_controller.go
  pkg/controller/noobaaaccount/noobaaaccount_controller.go
  pkg/cosi/cosi_bucket_access.go
  pkg/cosi/cosi_bucket_claim.go
  pkg/crd/crd.go
  pkg/diagnostics/analyze.go
  pkg/namespacestore/namespacestore.go
  pkg/noobaaaccount/noobaaaccount.go
  pkg/obc/obc.go
  pkg/system/autoscaler.go
  pkg/system/system.go
  pkg/util/util.go
Labels: size/XXL

#1208 [5.13] Bump version to 5.13.3
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1207 [Backport to 5.14] Add support for config file and bump rook
  .gitignore
  deploy/crds/noobaa.io_backingstores.yaml
  deploy/crds/noobaa.io_noobaas.yaml
  go.mod
  go.sum
  pkg/backingstore/backingstore.go
  pkg/bucketclass/bucketclass.go
  pkg/bundle/deploy.go
  pkg/cli/cli.go
  pkg/controller/backingstore/backingstore_controller.go
  pkg/controller/bucketclass/bucketclass_controller.go
  pkg/controller/cephcluster/cephcluster_controller.go
  pkg/controller/ha/ha_controller.go
  pkg/controller/namespacestore/namespacestore_controller.go
  pkg/controller/noobaa/noobaa_controller.go
  pkg/controller/noobaaaccount/noobaaaccount_controller.go
  pkg/cosi/cosi_bucket_access.go
  pkg/cosi/cosi_bucket_claim.go
  pkg/crd/crd.go
  pkg/diagnostics/analyze.go
  pkg/namespacestore/namespacestore.go
  pkg/noobaaaccount/noobaaaccount.go
  pkg/obc/obc.go
  pkg/system/autoscaler.go
  pkg/system/system.go
  pkg/util/util.go
Labels: size/XXL

#1211 [Backport to 4.14] fix obc with replication cli creation and validation
  pkg/cosi/cosi_bucket_claim.go
  pkg/cosi/provisioner.go
  pkg/cosi/validation.go
  pkg/obc/obc.go
  pkg/obc/provisioner.go
  pkg/obc/validation.go
  pkg/validations/common_bucket_validation_integ_test.go
  pkg/validations/common_bucket_validations.go
Labels: size/M

#1212 Bump version to 5.15
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S
