Repository noobaa/noobaa-operator, pull requests merged in 2023-03, with the labels that each got.

#1062 Fix Bug BZ 2149872, 1066 | Add Toleration And Affinity to Backingstore Pod after Editing Noobaa CR
  pkg/backingstore/backingstore.go
  pkg/backingstore/reconciler.go
  pkg/controller/backingstore/backingstore_controller.go
  pkg/obc/provisioner.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
  pkg/system/system.go
  pkg/util/util.go
Labels: size/L

#1067 Noobaa bucket quota alerts are not working
  deploy/internal/prometheus-rules.yaml
  pkg/bundle/deploy.go
Labels: size/M

#1063 CI | Update Admission Tests Workflow
  .github/workflows/run_admission_test.yml
  .travis/number_of_pods_in_system.sh
Labels: size/M

#1077 [backport to 5.11] Prompting more readable error when we get CONNECTED_BUCKET_DELETING
  .github/workflows/golangci-lint.yml
  pkg/validations/backingstore_validations.go
Labels: size/S

#1076 Admission test - release NooBaa core image
  .github/workflows/run_admission_test.yml
Labels: size/S

#1069 add security context to NooBaa operator pod
  deploy/operator.yaml
  pkg/bundle/deploy.go
Labels: size/S
