Repository noobaa/noobaa-operator, pull requests merged in 2023-06, with the labels that each got.

#1120 Fix incorrect function ListAccountsAPI()
  pkg/nb/api.go
  pkg/nb/types.go
Labels: size/S

#1134 bumped version to 5.14.0
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1137 Refactoring | re-use of code
  Makefile
  pkg/bucketclass/bucketclass.go
  pkg/bucketclass/reconciler.go
  pkg/obc/provisioner.go
  pkg/obc/validation.go
  pkg/util/util.go
  pkg/validations/bucketclass_validation.go
  pkg/validations/common_bucket_validation_integ_test.go
  pkg/validations/common_bucket_validations.go
  pkg/validations/validations_suite_test.go
Labels: size/L

#1139 Bug Fix #1135 BZ 2214288 | Remove Printing inside `rpc_WS` to Avoid Race Condition
  pkg/nb/rpc_ws.go
Labels: size/XS

#1141 COSI | Enable downstream cosi side car image replacement
  Makefile
  build/gen-odf-package.sh
  pkg/options/options.go
Labels: size/XS

#1145 [Backport to 5.12] remove printing inside rpc_ws to avoid race condition
  pkg/nb/rpc_ws.go
Labels: size/XS

#1146 [backport to 5.13] remove printing inside rpc_ws to avoid race condition
  pkg/nb/rpc_ws.go
Labels: size/XS
