Repository noobaa/noobaa-operator, pull requests merged in 2023-04, with the labels that each got.

#1083 [backport to 5.10] Prompting more readable error when we get CONNECTED_BUCKET_DELETING
  pkg/validations/backingstore_validations.go
Labels: size/XS

#1084 Bump go version from 1.18 to 1.19 and rook to v1.11.0
  .github/workflows/manual-build.yml
  .github/workflows/run_admission_test.yml
  .github/workflows/run_ci.yml
  .github/workflows/run_hac_test.yml
  .github/workflows/run_kms_dev_test.yml
  .github/workflows/run_kms_ibm_kp_test.yml
  .github/workflows/run_kms_kmip_test.yml
  .github/workflows/run_kms_tls_sa_test.yml
  .github/workflows/run_kms_tls_token_test.yml
  .github/workflows/testing.yml
  deploy/crds/noobaa.io_backingstores_crd.yaml
  deploy/crds/noobaa.io_noobaas_crd.yaml
  go.mod
  go.sum
  pkg/bundle/deploy.go
  pkg/obc/provisioner.go
Labels: size/L

#1085 [Backport into 5.13] dependency bump, go version from 1.18 to 1.19, and rook to 1.11.0
  .github/workflows/manual-build.yml
  .github/workflows/run_admission_test.yml
  .github/workflows/run_ci.yml
  .github/workflows/run_hac_test.yml
  .github/workflows/run_kms_dev_test.yml
  .github/workflows/run_kms_ibm_kp_test.yml
  .github/workflows/run_kms_kmip_test.yml
  .github/workflows/run_kms_tls_sa_test.yml
  .github/workflows/run_kms_tls_token_test.yml
  .github/workflows/testing.yml
  deploy/crds/noobaa.io_backingstores_crd.yaml
  deploy/crds/noobaa.io_noobaas_crd.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  pkg/bundle/deploy.go
  pkg/obc/provisioner.go
Labels: size/XL

#1086 Fix Bug BZ 2183480 | Update AWS Regions
  pkg/util/util.go
Labels: size/S

#1088 github action: bump golangci lint version
  .github/workflows/golangci-lint.yml
Labels: size/XS

#1078 Replace ownership change init container with K8s FSGroup
  deploy/internal/statefulset-db.yaml
  deploy/internal/statefulset-postgres-db.yaml
  deploy/scc_db.yaml
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
Labels: size/M

#1087 [5.13 backport] update aws regions
  .github/workflows/golangci-lint.yml
  pkg/util/util.go
Labels: size/S

#1091 [Backport to 5.13] remove ownership change init container
  deploy/internal/statefulset-db.yaml
  deploy/internal/statefulset-postgres-db.yaml
  deploy/scc_db.yaml
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
Labels: size/M

#1092 Bug Fix 1089 | `account-name` And `account-key` Should Not Appear When Creating azure-blob Namespacestore or Backingstore
  pkg/backingstore/backingstore.go
  pkg/namespacestore/namespacestore.go
Labels: size/XS

#1094 added --dev flag to the cli
  pkg/options/options.go
  pkg/system/system.go
Labels: size/M

#1090 Bumping rook to v1.11.3 and bump deps to avoid CVE
  go.mod
  go.sum
Labels: size/L

#1093 CI | Exclude 'docs' Directory From GitHub Workflows
  .github/workflows/golangci-lint.yml
  .github/workflows/run_admission_test.yml
  .github/workflows/run_ci.yml
  .github/workflows/run_hac_test.yml
  .github/workflows/run_kms_dev_test.yml
  .github/workflows/run_kms_ibm_kp_test.yml
  .github/workflows/run_kms_kmip_test.yml
  .github/workflows/run_kms_tls_sa_test.yml
  .github/workflows/run_kms_tls_token_test.yml
  .github/workflows/testing.yml
Labels: size/M

#1023 Integrate with KEDA for custom metrics scaling
  deploy/cluster_role.yaml
  deploy/crds/noobaa.io_noobaas_crd.yaml
  deploy/internal/hpa-keda-scaled-object.yaml
  deploy/internal/hpa-keda-secret.yaml
  deploy/internal/hpa-keda-trigger-authentication.yaml
  deploy/role.yaml
  go.mod
  go.sum
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/deploy.go
  pkg/options/options.go
  pkg/system/autoscaler.go
  pkg/system/phase1_verifying.go
  pkg/system/phase4_configuring.go
  pkg/system/reconciler.go
  pkg/system/system.go
  pkg/util/util.go
  pkg/validations/noobaa_validation.go
Labels: size/XL

#1099 [backport into 5.13] bumping rook to v1.11.3 to avoid CVE
  go.mod
  go.sum
  pkg/options/options.go
  pkg/system/system.go
Labels: size/L

#1103 CI | Undo Exclude Doc Directory from CI
  .github/workflows/golangci-lint.yml
  .github/workflows/run_admission_test.yml
  .github/workflows/run_ci.yml
  .github/workflows/run_hac_test.yml
  .github/workflows/run_kms_dev_test.yml
  .github/workflows/run_kms_ibm_kp_test.yml
  .github/workflows/run_kms_kmip_test.yml
  .github/workflows/run_kms_tls_sa_test.yml
  .github/workflows/run_kms_tls_token_test.yml
  .github/workflows/testing.yml
Labels: size/M

#1106 [Backport 5.12] add security context to NooBaa operator pod
  deploy/operator.yaml
  pkg/bundle/deploy.go
Labels: size/S

#1104 Fix init container cleanup, Rollback lib-bucket-provisioner, Fix autoscaler
  go.mod
  go.sum
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
  pkg/util/util.go
Labels: size/M

#1107 [Backport to 5.13] Rollback lib-bucket-prov, fix DB STS cleanup and defaults
  go.mod
  go.sum
  pkg/system/phase2_creating.go
  pkg/util/util.go
Labels: size/M

#1108 Noobaa CR valiation Fix
  pkg/system/phase1_verifying.go
  pkg/system/phase2_creating.go
  pkg/validations/noobaa_validation.go
Labels: size/S

#1110 Fix DB SCC reconcile
  pkg/system/phase2_creating.go
  pkg/util/util.go
Labels: size/XS
