Repository noobaa/noobaa-operator, pull requests merged in 2023-10, with the labels that each got.

#1214 Implement upgrade via CLI
  pkg/cli/cli.go
  pkg/crd/crd.go
  pkg/install/install.go
  pkg/operator/operator.go
  pkg/system/system.go
Labels: enhancement, size/L

#1223 Bug Fix BZ 2242854 | Fallback to PV Pool (CCO)
  pkg/system/phase4_configuring.go
Labels: size/M

#1215 Added support for force_md5_etag for bucket and account
  deploy/crds/noobaa.io_noobaaaccounts.yaml
  pkg/apis/noobaa/v1alpha1/noobaaaccount_types.go
  pkg/bucket/bucket.go
  pkg/bundle/deploy.go
  pkg/nb/types.go
  pkg/noobaaaccount/noobaaaccount.go
  pkg/options/options.go
Labels: size/M

#1227 Update documentation with SSL
  doc/external-postgres.md
Labels: size/M

#1230 Bug Fix BZ 2242414 | Add Flag `app-namespace` To Command `obc regenerate`
  pkg/noobaaaccount/noobaaaccount.go
  pkg/obc/obc.go
Labels: size/S

#1231 Bug Fix BZ 2242414 | Use `appNamespace` Instead of `options.Namespace` For Secret
  pkg/obc/obc.go
Labels: size/XS

#1232 Update Package github.com/openshift/api
  go.mod
  go.sum
Labels: size/M

#1229 CI | Increase Timeout In run_admission_test
  .github/workflows/run_admission_test.yml
Labels: size/XS

#1233 Pull busl to mpl licensing changes in libopenstorage to go.mod
  go.mod
  go.sum
Labels: size/L

#1239 [5.13] Bump version to 5.13.5
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1235 [backport to 5.13] BugFix - [MCG] RPC method "list_objects" fails with "RPC: object.list_objects() Call failed: failed to WebSocket dial"
  pkg/nb/router.go
Labels: size/XS
