Repository noobaa/noobaa-operator, pull requests merged in 2023-02, with the labels that each got.

#1041 Fix kmip test
  pkg/util/kms/test/kmip/pykmip/Dockerfile
Labels: size/XS

#1049 Fix Bug #1043 | Noobaa Account Status of admin@noobaa.io
  pkg/noobaaaccount/noobaaaccount.go
Labels: size/XS

#1042 [5.12] Backport automated releaser
  .github/workflows/releaser.yaml
  build/Dockerfile
  build/tools/builder-pre.sh
  build/tools/builder.sh
  build/tools/releaser-post.sh
  build/tools/releaser.sh
  build/tools/utils.sh
  pkg/util/kms/test/kmip/pykmip/Dockerfile
Labels: size/XL

#1016 [Direct on 5.12] Bump goutils v1.1.0 -> v1.1.1
  go.mod
  go.sum
Labels: size/XS

#1052 Fix releaser... again
  build/tools/builder-pre.sh
  build/tools/utils.sh
Labels: size/XS

#1053 [5.12] Backport releaser fixes and KMIP fix
  .travis/install-kmip-kms-noobaa.sh
  build/tools/builder-pre.sh
  build/tools/utils.sh
Labels: size/XS

#1036 Added CLI command to update noobaa account for default resource
  pkg/noobaaaccount/noobaaaccount.go
  test/cli/test_cli_functions.sh
Labels: size/L

#1054 default access mode of blob storage in noobaa should be private
  pkg/system/azure_utils.go
Labels: size/XS

#1055 [Backport to 5.12] default access mode of blob storage in noobaa should be private
  pkg/system/azure_utils.go
Labels: size/XS

#1056 [Backport to 5.11] default access mode of blob storage in noobaa should be private
  pkg/system/azure_utils.go
Labels: size/XS

#1057 [Backport to 5.10] default access mode of blob storage in noobaa should be private
  pkg/system/azure_utils.go
Labels: size/XS

#1046 Admission Tests Changes - Integration and Workflow
  .github/workflows/run_admission_test.yml
  pkg/admission/test/integ/admission_integ_test.go
Labels: size/L

#1060 Bug Fix #1040 | Add Namespace Option in Db-Dump (Not Only Default) In PG DB Only
  pkg/dbdump/dbdump.go
Labels: size/XS

#1033 Bug Fix #1007 | Default backing store avoid phase Ready with mode INITIALIZING
  pkg/backingstore/reconciler.go
Labels: size/S
