Repository noobaa/noobaa-operator, pull requests merged in 2023-07, with the labels that each got.

#1142 update noobaa endpoint replication
  deploy/internal/hpa-keda-scaled-object.yaml
  deploy/internal/hpav2-autoscaling.yaml
  pkg/bundle/deploy.go
  pkg/system/autoscaler.go
  pkg/system/reconciler.go
Labels: size/M

#1152 CPU utilization for HPA
  deploy/internal/hpa-keda-scaled-object.yaml
  deploy/internal/hpav2-autoscaling.yaml
  pkg/bundle/deploy.go
  pkg/system/autoscaler.go
Labels: size/L

#1144 Adding ca-inject to the operator yaml as optional, and add it to rootCAs list
  deploy/operator.yaml
  pkg/bundle/deploy.go
  pkg/util/util.go
Labels: size/M

#1147 COSI | CLI | bucketclass & bucketclaim support
  deploy/cosi/bucket_class.yaml
  deploy/cosi/cosi_bucket.yaml
  doc/cosi-provisioner.md
  go.mod
  go.sum
  pkg/apis/noobaa/v1alpha1/cosi_types.go
  pkg/bucketclass/bucketclass.go
  pkg/bundle/deploy.go
  pkg/cli/cli.go
  pkg/cosi/cosi.go
  pkg/cosi/cosi_bucket_claim.go
  pkg/cosi/cosi_bucket_class.go
  pkg/cosi/cosi_cli_test.go
  pkg/cosi/provisioner.go
  pkg/cosi/validation.go
  pkg/util/util.go
Labels: size/XXL

#1156 fixed default cosi image for make gen-odf-package
  Makefile
  build/gen-odf-package.sh
Labels: size/XS

#1172 Fixing issue with bounded COSI socket
  pkg/cosi/provisioner.go
  pkg/options/options.go
Labels: size/S

#1138 Endpoints topology-spread-constraints added
  doc/noobaa-crd.md
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/system/phase4_configuring.go
  pkg/util/util.go
Labels: size/M

#1177 Backport to 5.14
  pkg/backingstore/reconciler.go
  pkg/namespacestore/reconciler.go
  pkg/nb/types.go
Labels: size/M

#1161 COSI | CLI | Bucket Access Class & Bucket Access implementation
  doc/cosi-provisioner.md
  pkg/apis/noobaa/v1alpha1/cosi_types.go
  pkg/cosi/cosi.go
  pkg/cosi/cosi_access_class.go
  pkg/cosi/cosi_bucket_access.go
  pkg/cosi/cosi_bucket_claim.go
  pkg/cosi/cosi_bucket_class.go
  pkg/cosi/cosi_cli_test.go
Labels: size/XL

#1179 Adding basic support for working with external postgres DB
  deploy/crds/noobaa.io_noobaas_crd.yaml
  deploy/internal/deployment-endpoint.yaml
  deploy/internal/statefulset-core.yaml
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/deploy.go
  pkg/options/options.go
  pkg/system/phase2_creating.go
  pkg/system/reconciler.go
  pkg/system/system.go
Labels: size/L

#1182 [backport to 5.14] bucket access class impl
  doc/cosi-provisioner.md
  pkg/apis/noobaa/v1alpha1/cosi_types.go
  pkg/cosi/cosi.go
  pkg/cosi/cosi_access_class.go
  pkg/cosi/cosi_bucket_access.go
  pkg/cosi/cosi_bucket_claim.go
  pkg/cosi/cosi_bucket_class.go
  pkg/cosi/cosi_cli_test.go
Labels: size/XL

#1180 Update `ContainerImage` to point to the latest build
  pkg/options/options.go
Labels: size/XS

#1097 Add Deploy Noobaa On Minikube or Rancher Desktop Documentation (For Developers)
  doc/dev_guide/deply_noobaa_on_minikube_or_rancher_desktop.md
Labels: size/L
