Repository noobaa/noobaa-operator, pull requests merged in 2023-11, with the labels that each got.

#1236 [Backport to 5.12] BugFix - [MCG] RPC method "list_objects" fails with "RPC: object.list_objects() Call failed: failed to WebSocket dial"
  pkg/nb/router.go
  pkg/options/options.go
Labels: size/XS

#1237 [Backport to 5.11] BugFix - [MCG] RPC method "list_objects" fails with "RPC: object.list_objects() Call failed: failed to WebSocket dial"
  pkg/nb/router.go
Labels: size/XS

#1240 [Backport to 5.13] fix - fallback to pv pool (cco)
  pkg/system/phase4_configuring.go
Labels: size/M

#1246 Add Logs to `Setdesirednoobaadb` Before Record an Event
  pkg/system/phase2_creating.go
Labels: size/XS

#1247 Edit CLI Short of Creation of Type `aws-sts-s3` in BS and NS
  pkg/backingstore/backingstore.go
  pkg/namespacestore/namespacestore.go
Labels: size/S

#1245 Default Backingstore IBM COS - Change Comment and Variable Name
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
  pkg/system/reconciler.go
  pkg/util/util.go
Labels: size/M

#1250 [5.14] Bump version from 5.14.0 to 5.14.1
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1242 [Backport into 5.14] Regenerating s3 credentials for OBC not in a different namespace fails
  pkg/noobaaaccount/noobaaaccount.go
  pkg/obc/obc.go
Labels: size/S
