Repository noobaa/noobaa-operator, pull requests merged in 2024-01, with the labels that each got.

#1264 [Clone] Add upgrade process for postgres DB version 15
  Makefile
  build/gen-odf-package.sh
  deploy/crds/noobaa.io_noobaas.yaml
  deploy/internal/configmap-postgres-initdb.yaml
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/deploy.go
  pkg/olm/olm.go
  pkg/options/options.go
  pkg/system/phase2_creating.go
Labels: size/L

#1277 [Backport to 5.15] Add upgrade process for postgres DB version 15
  Makefile
  build/gen-odf-package.sh
  deploy/crds/noobaa.io_noobaas.yaml
  deploy/internal/configmap-postgres-initdb.yaml
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/deploy.go
  pkg/olm/olm.go
  pkg/options/options.go
  pkg/system/phase2_creating.go
Labels: size/L

#1281 [backport to 5.15] Fix the label-based IBM cluster region lookup (#1279)
  pkg/util/util.go
Labels: size/XS

#1280 update rook to 1.13.1 as part of noobaa operator dependency
  go.mod
  go.sum
  pkg/operator/manager.go
Labels: size/XL

#1241 Fix - Added force_md5_etag in NoobaaAccount CmdUpdate
  pkg/apis/noobaa/v1alpha1/noobaaaccount_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/nb/types.go
  pkg/noobaaaccount/noobaaaccount.go
  pkg/noobaaaccount/reconciler.go
Labels: size/S

#1283 [Backport into 5.15] update rook to 1.31.1
  .github/workflows/golangci-lint.yml
  go.mod
  go.sum
  pkg/operator/manager.go
Labels: size/XL

#1252 Set quota directly on a bucket
  pkg/bucket/bucket.go
Labels: size/M

#1286 [5.15] - CLI Additions
  pkg/apis/noobaa/v1alpha1/noobaaaccount_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bucket/bucket.go
  pkg/nb/types.go
  pkg/noobaaaccount/noobaaaccount.go
  pkg/noobaaaccount/reconciler.go
Labels: size/M

#1278 Adding document on PgSql upgrade procedure
  doc/psql15-upgrade.md
Labels: size/M

#1287 Fix - don't run db 15 upgrade for mongoDB
  pkg/system/phase2_creating.go
Labels: size/XS

#1290 [5.13] Bump version to 5.13.7
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1289 [5.14] Bumping version from 5.14.3 to 5.14.4
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1291 Remove upgradeBackingStore
  pkg/backingstore/backingstore.go
  pkg/backingstore/reconciler.go
Labels: size/M

#1293 [Backport into 5.15] backporting some bug fixes
  doc/psql15-upgrade.md
  pkg/backingstore/backingstore.go
  pkg/backingstore/reconciler.go
  pkg/system/phase2_creating.go
  pkg/system/system.go
Labels: size/L

#1294 [5.14] Bumping the version from 5.14.4 to 5.14.5
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1292 Moving COSI temporarily out of the code
  .github/workflows/run_cosi_test.yaml
  deploy/operator.yaml
  pkg/bundle/deploy.go
  pkg/controller/add_cosi.go
  pkg/operator/operator.go
Labels: size/L

#1249 Noobaa/Bucket Logging : syslog service for log transfer
  deploy/crds/noobaa.io_noobaas.yaml
  deploy/internal/deployment-endpoint.yaml
  deploy/internal/service-syslog.yaml
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
  pkg/system/reconciler.go
Labels: size/L

#1295 CI | Update Checkout and Setup-Go Version
  .github/workflows/golangci-lint.yml
  .github/workflows/manual-build.yml
  .github/workflows/releaser.yaml
  .github/workflows/run_admission_test.yml
  .github/workflows/run_ci.yml
  .github/workflows/run_cosi_test.yaml
  .github/workflows/run_hac_test.yml
  .github/workflows/run_kms_dev_test.yml
  .github/workflows/run_kms_ibm_kp_test.yml
  .github/workflows/run_kms_kmip_test.yml
  .github/workflows/run_kms_rotate_test.yml
  .github/workflows/run_kms_tls_sa_test.yml
  .github/workflows/run_kms_tls_token_test.yml
  .github/workflows/testing.yml
Labels: size/M

#1297 [Backport into 5.14] Remove upgradeBackingStore
  pkg/backingstore/backingstore.go
  pkg/backingstore/reconciler.go
Labels: size/M

#1296 [5.13] Bump version to 5.13.8
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S
