Repository noobaa/noobaa-operator, pull requests merged in 2024-04, with the labels that each got.

#1330 [5.14] Bumping version from 5.14.6 to 5.14.7
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1329 Removed Mongo related code and files
  README.md
  deploy/crds/noobaa.io_noobaas.yaml
  deploy/internal/deployment-endpoint.yaml
  deploy/internal/job-upgrade-db.yaml
  deploy/internal/service-db.yaml
  deploy/internal/statefulset-core.yaml
  deploy/internal/statefulset-db.yaml
  doc/noobaa-crd.md
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/bundle/deploy.go
  pkg/diagnostics/dbdump.go
  pkg/options/options.go
  pkg/system/phase1_verifying.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
  pkg/system/reconciler.go
  pkg/system/system.go
  test/cli/test_cli_flow.sh
Labels: size/XXL

#1332 Adding disable_cookies annotation to S3 route
  deploy/internal/route-s3.yaml
  pkg/bundle/deploy.go
Labels: size/XS

#1331 Removed Postgres upgrade code (12 to 15)
  Makefile
  README.md
  build/gen-odf-package.sh
  pkg/olm/olm.go
  pkg/options/options.go
  pkg/system/phase2_creating.go
Labels: size/L

#1333 Bump version to 5.17.0
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1334 [5.13] Bump version to 5.13.9
  .github/workflows/golangci-lint.yml
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1317 removed init container for Postgres DB pod
  deploy/internal/configmap-postgres-initdb.yaml
  deploy/internal/statefulset-postgres-db.yaml
  deploy/role_db.yaml
  deploy/scc_db.yaml
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
  pkg/system/reconciler.go
Labels: size/XL

#1335 Fixing reconcile for mounted root-key secret noobaa-root-master-key-volume
  pkg/system/phase2_creating.go
Labels: size/S

#1338 [5.15] Bumping version from 5.15.1 to 5.15.2
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1341 Fix default resource request/limit for PV pool pods
  deploy/internal/pod-agent.yaml
  pkg/bundle/deploy.go
Labels: size/S

#1343 Fixing AzureClientCertPath in kms for azure
  pkg/util/kms/kms_azure.go
  pkg/util/kms/test/azure-vault/kms_azure_vault_test.go
Labels: size/M

#1345 [Backport into 5.14] Fix the label-based IBM cluster region lookup (#1279)
  pkg/util/util.go
Labels: size/XS

#1348 Updating Rook to v0.0.0-20240327231646-b6b89a012a95
  deploy/crds/noobaa.io_backingstores.yaml
  deploy/crds/noobaa.io_noobaas.yaml
  go.mod
  go.sum
  pkg/admission/test/integ/admission_integ_test.go
  pkg/admission/test/unit/admission_unit_test.go
  pkg/apis/noobaa/v1alpha1/backingstore_types.go
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/backingstore/backingstore.go
  pkg/bundle/deploy.go
  pkg/system/phase4_configuring.go
  pkg/system/system.go
Labels: size/XL

#1340 SCC fixes
  deploy/internal/pod-agent.yaml
  deploy/internal/statefulset-core.yaml
  deploy/internal/statefulset-postgres-db.yaml
  deploy/role.yaml
  deploy/scc.yaml
  deploy/scc_db.yaml
  deploy/scc_endpoint.yaml
  pkg/bundle/deploy.go
Labels: size/M
