Repository noobaa/noobaa-operator, pull requests merged in 2024-12, with the labels that each got.

#1482 Noobaa/Operator: Display error message
  pkg/bucketclass/bucketclass.go
  pkg/obc/obc.go
  test/cli/test_cli_functions.sh
Labels: size/S

#1484 [Backport into 5.18] Noobaa/Operator: Display error message
  pkg/bucketclass/bucketclass.go
  pkg/obc/obc.go
  test/cli/test_cli_functions.sh
Labels: size/S

#1485 bucket notification - check pvcName, not pvc DFBUGS 988, 991
  pkg/system/phase2_creating.go
Labels: size/XS

#1483 Bug-fix for fetching region from AWS cluster obj in GetAWSRegion()
  deploy/cluster_role.yaml
  pkg/bundle/deploy.go
  pkg/util/util.go
Labels: size/M

#1491 [Backport into 5.18] bucket notification - check pvcName, not pvc DFBUGS 988, 991 (#1485)
  pkg/system/phase2_creating.go
Labels: size/XS

#1492 [Backport into 5.18] Bug-fix for fetching region from AWS cluster obj in GetAWSRegion()
  README.md
  deploy/cluster_role.yaml
  doc/bucket-types.md
  pkg/bundle/deploy.go
  pkg/util/util.go
  test/cli/test_cli_functions.sh
Labels: size/L

#1498 [5.16] Bumping version from 5.16.4 to 5.16.5
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1494 Bucket Notification - connect filename simplification
  pkg/system/phase2_creating.go
Labels: size/XS

#1499 BACKPORT Bucket Notification - connect filename simplification (#1494)
  pkg/system/phase2_creating.go
Labels: size/XS
