Repository noobaa/noobaa-operator, pull requests merged in 2024-11, with the labels that each got.

#1469 [5.17] Bumping version from 5.17.0 to 5.17.1
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1468 [5.16] Bumping version from 5.16.3 to 5.16.4
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1470 [Backport into 5.17] CI | Fixing deprecated linter
  .github/workflows/golangci-lint.yml
  .golangci.yml
  Makefile
  pkg/backingstore/backingstore.go
  pkg/bucketclass/bucketclass.go
  pkg/cosi/provisioner.go
  pkg/install/install.go
  pkg/namespacestore/namespacestore.go
  pkg/nb/rpc_ws.go
  pkg/noobaaaccount/noobaaaccount.go
  pkg/obc/obc.go
  pkg/obc/provisioner.go
  pkg/system/reconciler.go
  pkg/util/kms/test/dev/kms_dev_test.go
  pkg/util/kms/test/ibm-kp/kms_ibm_kp_test.go
Labels: size/L

#1471 [Backport into 5.16] CI | Fixing deprecated linter
  .github/workflows/golangci-lint.yml
  .golangci.yml
  Makefile
  pkg/backingstore/backingstore.go
  pkg/bucketclass/bucketclass.go
  pkg/cosi/provisioner.go
  pkg/install/install.go
  pkg/namespacestore/namespacestore.go
  pkg/nb/rpc_ws.go
  pkg/noobaaaccount/noobaaaccount.go
  pkg/obc/obc.go
  pkg/obc/provisioner.go
  pkg/system/reconciler.go
  pkg/util/kms/test/dev/kms_dev_test.go
  pkg/util/kms/test/ibm-kp/kms_ibm_kp_test.go
Labels: size/L

#1462 Added ARN checks in the diagnostics report
  pkg/diagnostics/report.go
Labels: size/M

#1457 kms: Root key rotation for Vault KMS
  pkg/system/phase2_creating.go
  pkg/util/kms/kms_vault.go
  pkg/util/kms/kms_version.go
  pkg/util/kms/test/dev/kms_dev_test.go
  pkg/util/kms/test/tls-sa/kms_tls_sa_test.go
  pkg/util/kms/test/tls-token/kms_tls_token_test.go
Labels: size/L

#1473 Adapting operator to new bucket list API change
  pkg/bucket/bucket.go
  pkg/nb/api.go
  pkg/nb/types.go
Labels: size/S

#1467 Bucket Notifcations
  deploy/crds/noobaa.io_noobaas.yaml
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/deploy.go
  pkg/system/phase1_verifying.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
  pkg/system/reconciler.go
Labels: size/L
