Repository noobaa/noobaa-operator, pull requests merged in 2024-05, with the labels that each got.

#1353 Fix printing of Identity
  pkg/backingstore/reconciler.go
  pkg/namespacestore/reconciler.go
  pkg/nb/types.go
Labels: size/M

#1354 [5.15] Bump version to 5.15.3
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1356 Fix for mount permissions on the agents PV
  deploy/internal/pod-agent.yaml
  deploy/internal/statefulset-postgres-db.yaml
  pkg/bundle/deploy.go
Labels: size/S

#1355 [Backport | 5.15] SCC fixes
  deploy/internal/pod-agent.yaml
  deploy/internal/statefulset-postgres-db.yaml
  deploy/role.yaml
  deploy/scc.yaml
  deploy/scc_db.yaml
  deploy/scc_endpoint.yaml
  pkg/bundle/deploy.go
Labels: size/M

#1357 Fixed AccessKeys printings on RPC calls
  pkg/cosi/provisioner.go
  pkg/nb/types.go
  pkg/noobaaaccount/noobaaaccount.go
  pkg/noobaaaccount/reconciler.go
  pkg/obc/obc.go
  pkg/obc/provisioner.go
  pkg/system/phase4_configuring.go
Labels: size/M

#1359 [5.15] SCC Fix
  deploy/scc_db.yaml
  pkg/bundle/deploy.go
Labels: size/XS

#1360 README.md typo fix
  README.md
Labels: size/XS

#1344 Support to update credentials manually to an account
  pkg/nb/api.go
  pkg/nb/types.go
  pkg/noobaaaccount/noobaaaccount.go
  pkg/options/options.go
  pkg/util/util.go
  test/cli/test_cli_functions.sh
Labels: size/L

#1363 Fixed type casting for GenerateNonCrdAccountKeys
  pkg/noobaaaccount/noobaaaccount.go
Labels: size/XS

#1364 Bump dependencies
  go.mod
  go.sum
Labels: size/L

#1362 Added BucketLogging type to enable different types of bucket logging
  deploy/crds/noobaa.io_noobaas.yaml
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/deploy.go
Labels: size/M

#1369 [5.14] Bumping version from 5.14.7 to 5.14.8
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S
