Repository noobaa/noobaa-operator, pull requests merged in 2024-03, with the labels that each got.

#1308 [5.15 BACKPORT] Utilize the refreshing global CA bundle for the Azure and Google clients
  pkg/system/azure_utils.go
  pkg/system/phase4_configuring.go
  pkg/util/util.go
Labels: size/M

#1309 Doc | Update Readme Flags
  README.md
Labels: size/XS

#1310 Update AWS Regions with New Region
  pkg/util/util.go
Labels: size/XS

#1314 Partial revert of #1304
  pkg/system/phase4_configuring.go
Labels: size/S

#1315 [BACKPORT 5.15] Partial revert of #1304
  pkg/system/phase4_configuring.go
Labels: size/S

#1313 [5.14] Bumping the version from 5.14.5 to 5.14.6
  .github/workflows/golangci-lint.yml
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1318 Adding denyHTTP option to NooBaa CR
  deploy/crds/noobaa.io_noobaas.yaml
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
Labels: size/S

#1319 [DB Upgrade] Fixing returned status and adding prints
  pkg/system/phase2_creating.go
Labels: size/S

#1320 [Backport to 5.15] fixing returned status and adding prints
  pkg/system/phase2_creating.go
Labels: size/S

#1323 Bump dependencies
  go.mod
  go.sum
Labels: size/M

#1324 update go version to v1.21
  .github/workflows/manual-build.yml
  .github/workflows/releaser.yaml
  .github/workflows/run_admission_test.yml
  .github/workflows/run_ci.yml
  .github/workflows/run_cosi_test.yaml
  .github/workflows/run_hac_test.yml
  .github/workflows/run_kms_dev_test.yml
  .github/workflows/run_kms_ibm_kp_test.yml
  .github/workflows/run_kms_kmip_test.yml
  .github/workflows/run_kms_rotate_test.yml
  .github/workflows/run_kms_tls_sa_test.yml
  .github/workflows/run_kms_tls_token_test.yml
  .github/workflows/testing.yml
  Makefile
  deploy/crds/noobaa.io_backingstores.yaml
  deploy/crds/noobaa.io_bucketclasses.yaml
  deploy/crds/noobaa.io_namespacestores.yaml
  deploy/crds/noobaa.io_noobaaaccounts.yaml
  deploy/crds/noobaa.io_noobaas.yaml
  go.mod
  go.sum
  pkg/bundle/deploy.go
Labels: size/XXL

#1303 bucket_logging: Bucket log processing in side car container
  deploy/crds/noobaa.io_noobaas.yaml
  deploy/internal/service-syslog.yaml
  deploy/internal/statefulset-core.yaml
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/deploy.go
  pkg/options/options.go
  pkg/system/phase2_creating.go
  pkg/system/system.go
Labels: size/L

#1311 Azure kms handling for noobaa
  .github/workflows/run_kms_azure_vault_test.yml
  .travis/install-noobaa-pull-azure-parameters.sh
  Makefile
  go.mod
  go.sum
  pkg/util/kms/kms_azure.go
  pkg/util/kms/kms_ibm_kp_storage.go
  pkg/util/kms/kms_kmip_storage.go
  pkg/util/kms/kms_version.go
  pkg/util/kms/test/azure-vault/kms_azure_vault_suite_test.go
  pkg/util/kms/test/azure-vault/kms_azure_vault_test.go
  pkg/util/kms/test/ibm-kp/kms_ibm_kp_test.go
Labels: size/XXL

#1326 [5.15] Bumping version from 5.15.0 to 5.15.1
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S
