Repository noobaa/noobaa-operator, pull requests merged in 2024-02, with the labels that each got.

#1257 Update README
  README.md
Labels: size/L

#1298 fixing error for collation external PG
  pkg/system/phase1_verifying.go
Labels: size/XS

#1300 [Backport to 5.15] use injected root CAs also when for AWS and IBM
  pkg/system/phase4_configuring.go
Labels: size/S

#1302 Bump version to 5.16.0
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1307 Update external-postgres.md - 'c' should be the correct one
  doc/external-postgres.md
Labels: size/XS

#1306 Doc | Add a Case in the Guide Troubleshoot AWS STS Cluster
  doc/dev_guide/troubleshoot_sts_cluster.md
Labels: size/S
