Repository noobaa/noobaa-operator, pull requests merged in 2024-10, with the labels that each got.

#1454 Fix #432: Change db service to headless needed to get direct pod dns name on GKE
  deploy/internal/service-db.yaml
  pkg/bundle/deploy.go
Labels: size/XS

#1456 Minor lint fixes
  pkg/obc/provisioner.go
Labels: size/S

#1459 [5.15] Bumping version from 5.15.7 to 5.15.8
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1458 [5.14] Bumping version from 5.14.11 to 5.14.12
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1460 [Backport to 5.15] Modify the handling of injected OCP CA bundles
  deploy/internal/configmap-ca-inject.yaml
  deploy/operator.yaml
  pkg/bundle/deploy.go
  pkg/olm/olm.go
  pkg/system/azure_utils.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
  pkg/util/util.go
Labels: size/M

#1461 Updating controller-runtime to v0.19.0
  Makefile
  deploy/crds/noobaa.io_backingstores.yaml
  deploy/crds/noobaa.io_bucketclasses.yaml
  deploy/crds/noobaa.io_namespacestores.yaml
  deploy/crds/noobaa.io_noobaaaccounts.yaml
  deploy/crds/noobaa.io_noobaas.yaml
  go.mod
  go.sum
  pkg/apis/noobaa/v1alpha1/register.go
  pkg/bundle/deploy.go
  pkg/controller/backingstore/backingstore_controller.go
  pkg/controller/bucketclass/bucketclass_controller.go
  pkg/controller/cephcluster/cephcluster_controller.go
  pkg/controller/namespacestore/namespacestore_controller.go
  pkg/controller/noobaa/noobaa_controller.go
  pkg/controller/noobaaaccount/noobaaaccount_controller.go
Labels: size/XL

#1464 Removing golangci-lint-action in favor or make lint
  .github/workflows/golangci-lint.yml
Labels: size/S

#1463 Fix Bug BZ 2320939 | Update AWS Regions
  pkg/util/util.go
Labels: size/XS

#1466 Docs | STS | Update Docs (Noobaa Core Service Account Name Changed)
  deploy/internal/deployment-endpoint.yaml
  deploy/internal/statefulset-core.yaml
  deploy/operator.yaml
  doc/dev_guide/create_aws_role.sh
  doc/dev_guide/troubleshoot_sts_cluster.md
  pkg/bundle/deploy.go
Labels: size/L
