Repository noobaa/noobaa-operator, pull requests merged in 2024-09, with the labels that each got.

#1423 Added annotation to CSV capabilities="Seamless Upgrades"
  pkg/olm/olm.go
Labels: size/XS

#1424 [Bakport to 5.17] added annotation to CSV capabilities="Seamless Upgrades"
  pkg/olm/olm.go
Labels: size/XS

#1426 [5.15] Bumping version from 5.15.6 to 5.15.7
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1427 Fix serviceAccount for noobaa-core
  deploy/role_binding_core.yaml
  deploy/role_core.yaml
  pkg/bundle/deploy.go
  pkg/operator/operator.go
  pkg/system/phase2_creating.go
Labels: size/M

#1428 [5.14] Bumping version from 5.14.10 to 5.14.11
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1429 [Backport into 5.15] Backport fixes
  deploy/crds/noobaa.io_noobaaaccounts.yaml
  deploy/internal/route-s3.yaml
  doc/obc-provisioner.md
  pkg/admission/test/unit/admission_unit_test.go
  pkg/apis/noobaa/v1alpha1/noobaaaccount_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/backingstore/reconciler.go
  pkg/bucketclass/bucketclass.go
  pkg/bundle/deploy.go
  pkg/cosi/cosi_bucket_class.go
  pkg/namespacestore/reconciler.go
  pkg/nb/types.go
  pkg/noobaaaccount/noobaaaccount.go
  pkg/obc/obc.go
  pkg/obc/provisioner.go
  pkg/obc/validation.go
  pkg/util/util.go
  pkg/validations/common_bucket_validation_integ_test.go
  pkg/validations/common_bucket_validations.go
  pkg/validations/noobaaaccount_validation.go
  test/cli/test_cli_flow.sh
  test/cli/test_cli_functions.sh
Labels: size/L

#1432 Disabling lint as a quick fix to release the CI flow.
  Makefile
Labels: size/S

#1431 [Backport to 5.17] Fix serviceAccount for noobaa-core
  Makefile
  deploy/role_binding_core.yaml
  deploy/role_core.yaml
  pkg/bundle/deploy.go
  pkg/operator/operator.go
  pkg/system/phase2_creating.go
Labels: size/M

#1433 [Backport into 5.16] Disabling lint as a quick fix to release the CI flow.
  Makefile
Labels: size/S

#1435 [Backport into 5.14] Disabling lint as a quick fix to release the CI flow.
  Makefile
Labels: size/S

#1434 [Backport into 5.15] Disabling lint as a quick fix to release the CI flow.
  Makefile
  test/cli/test_cli_flow.sh
Labels: size/S

#1400 [Backport into 5.14] adding disable_cookies annotation
  deploy/internal/route-s3.yaml
  pkg/bundle/deploy.go
Labels: size/XS

#1436 [Backport into 5.14] Moving COSI temporarily out of the code
  .github/workflows/run_cosi_test.yaml
  deploy/operator.yaml
  pkg/bundle/deploy.go
  pkg/controller/add_cosi.go
  pkg/operator/operator.go
Labels: size/L

#1437 [Backport into 5.14] Support user-provided NSFSAccountConfig when creating OBCs
  deploy/crds/noobaa.io_noobaaaccounts.yaml
  doc/obc-provisioner.md
  pkg/admission/test/unit/admission_unit_test.go
  pkg/apis/noobaa/v1alpha1/noobaaaccount_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bucketclass/bucketclass.go
  pkg/bundle/deploy.go
  pkg/cosi/cosi_bucket_class.go
  pkg/noobaaaccount/noobaaaccount.go
  pkg/obc/obc.go
  pkg/obc/provisioner.go
  pkg/obc/validation.go
  pkg/util/util.go
  pkg/validations/common_bucket_validation_integ_test.go
  pkg/validations/common_bucket_validations.go
  pkg/validations/noobaaaccount_validation.go
  test/cli/test_cli_flow.sh
  test/cli/test_cli_functions.sh
Labels: size/L

#1438 Fixing the CLI decision error handling to avoid lint errors
  pkg/backingstore/backingstore.go
  pkg/install/install.go
  pkg/namespacestore/namespacestore.go
  pkg/noobaaaccount/noobaaaccount.go
  pkg/obc/obc.go
Labels: size/M

#1439 CI | Using golangci-lint for lint in the Makefile target
  .golangci.yml
  Makefile
  pkg/backingstore/backingstore.go
  pkg/bucketclass/bucketclass.go
  pkg/cosi/provisioner.go
  pkg/namespacestore/namespacestore.go
  pkg/nb/rpc_ws.go
  pkg/obc/provisioner.go
  pkg/system/reconciler.go
  pkg/util/kms/test/dev/kms_dev_test.go
  pkg/util/kms/test/ibm-kp/kms_ibm_kp_test.go
Labels: size/M

#1441 Remove hardcoded namespace from rolebinding
  deploy/role_binding_core.yaml
  pkg/bundle/deploy.go
Labels: size/XS

#1442 [Backport 5.17] Remove hardcoded namespace from rolebinding
  deploy/role_binding_core.yaml
  pkg/bundle/deploy.go
Labels: size/XS

#1440 Added a CLI sub-command in noobaa diagnostics to print proxy details
  pkg/diagnostics/diagnostics.go
  pkg/diagnostics/report.go
Labels: size/M

#1443 CI | Update ginkgo to v2
  .github/workflows/run_admission_test.yml
  .github/workflows/run_cosi_test.yaml
  .github/workflows/run_hac_test.yml
  .github/workflows/run_kms_azure_vault_test.yml
  .github/workflows/run_kms_dev_test.yml
  .github/workflows/run_kms_ibm_kp_test.yml
  .github/workflows/run_kms_kmip_test.yml
  .github/workflows/run_kms_rotate_test.yml
  .github/workflows/run_kms_tls_sa_test.yml
  .github/workflows/run_kms_tls_token_test.yml
  go.mod
  go.sum
  pkg/admission/test/integ/admission_integ_test.go
  pkg/admission/test/integ/admission_suite_integ_test.go
  pkg/admission/test/unit/admission_suite_unit_test.go
  pkg/admission/test/unit/admission_unit_test.go
  pkg/controller/bucketclass/bucketclass_suite_test.go
  pkg/controller/bucketclass/bucketclass_test.go
  pkg/controller/ha/ha_suite_test.go
  pkg/controller/ha/hac_test.go
  pkg/cosi/cosi_cli_test.go
  pkg/cosi/cosi_suite_test.go
  pkg/cosi/cosi_test.go
  pkg/obc/obc_suite_test.go
  pkg/obc/obc_test.go
  pkg/operator/operator_suite_test.go
  pkg/operator/operator_test.go
  pkg/util/kms/test/azure-vault/kms_azure_vault_suite_test.go
  pkg/util/kms/test/azure-vault/kms_azure_vault_test.go
  pkg/util/kms/test/dev/kms_dev_suite_test.go
  pkg/util/kms/test/dev/kms_dev_test.go
  pkg/util/kms/test/ibm-kp/kms_ibm_kp_suite_test.go
  pkg/util/kms/test/ibm-kp/kms_ibm_kp_test.go
  pkg/util/kms/test/kmip/kms_kmip_suite_test.go
  pkg/util/kms/test/kmip/kms_kmip_test.go
  pkg/util/kms/test/rotate/kms_rotate_suite_test.go
  pkg/util/kms/test/rotate/kms_rotate_test.go
  pkg/util/kms/test/tls-sa/kms_tls_sa_suite_test.go
  pkg/util/kms/test/tls-sa/kms_tls_sa_test.go
  pkg/util/kms/test/tls-token/kms_tls_token_suite_test.go
  pkg/util/kms/test/tls-token/kms_tls_token_test.go
  pkg/util/predicates_test.go
  pkg/util/util_suite_test.go
  pkg/validations/common_bucket_validation_integ_test.go
  pkg/validations/validations_suite_test.go
Labels: size/L

#1444 [5.16] Bumping version from 5.16.2 to 5.16.3
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1446 NOOBAA_LOG_COLOR - Add check env var is not null
  pkg/backingstore/reconciler.go
Labels: size/XS

#1430 Updated forceMD5Etag to boolean pointer type
  pkg/bucket/bucket.go
  pkg/nb/types.go
  pkg/noobaaaccount/noobaaaccount.go
  pkg/noobaaaccount/reconciler.go
  pkg/util/util.go
Labels: size/M

#1418 Added a validation check for quota config in bucket
  pkg/bucket/bucket.go
Labels: size/M

#1445 Printing overrided vars in cli command `noobaa diagnostics report`
  pkg/diagnostics/report.go
Labels: size/M

#1450 Fix #432 POSTGRES_HOST use service url with namespace
  pkg/system/phase2_creating.go
Labels: size/XS

#1452 Add support for AllNamespaces install mode
  deploy/olm/noobaa-operator.clusterserviceversion.yaml
  pkg/bundle/deploy.go
Labels: size/XS
