Repository noobaa/noobaa-operator, pull requests merged in 2024-07, with the labels that each got.

#1385 Fix the VolumeMount path for bucket logging
  pkg/system/reconciler.go
Labels: size/XS

#1386 [5.15] Bump version to 5.15.4
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1387 [5.14] Bumping version from 5.14.9 to 5.14.10
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1390 Checking for pvc only if BucketLoggingPVC is not nil
  pkg/system/phase1_verifying.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
  pkg/system/reconciler.go
Labels: size/S

#1392 [5.16] Bumping version from 5.16.0 to 5.16.1
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1394 [Backport into 5.16] Bump github.com/hashicorp/go-retryablehttp from 0.7.6 to 0.7.7
  go.mod
  go.sum
Labels: size/S

#1395 [5.15] Bumping version from 5.15.4 to 5.15.6
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1391 Fixing SCC issues for bucket logging
  deploy/internal/statefulset-core.yaml
  deploy/role_binding_core.yaml
  deploy/role_core.yaml
  deploy/scc_endpoint.yaml
  deploy/service_account_core.yaml
  pkg/bundle/deploy.go
  pkg/olm/olm.go
  pkg/operator/operator.go
Labels: size/L

#1397 [Direct to 4.15] Set Noobaa status to rejected if failed to upgrade to postgresql-15
  pkg/system/reconciler.go
Labels: size/S

#1396 Keep using psql 12 if failed upgrading to psql15
  Makefile
  build/gen-odf-package.sh
  pkg/olm/olm.go
  pkg/options/options.go
  pkg/system/phase2_creating.go
  pkg/system/reconciler.go
  pkg/system/system.go
Labels: size/M

#1398 [Backport 5.16] Added a workaround for postgres upgrade failures
  Makefile
  build/gen-odf-package.sh
  pkg/olm/olm.go
  pkg/options/options.go
  pkg/system/phase2_creating.go
  pkg/system/reconciler.go
  pkg/system/system.go
Labels: size/M

#1393 Implement operator support for pool ownership
  deploy/internal/statefulset-core.yaml
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
  pkg/util/util.go
Labels: size/S

#1367 [Direct To 5.15] add InitCotnainers to DB sts if not exist
  pkg/system/phase2_creating.go
Labels: size/XS
