Repository noobaa/noobaa-operator, pull requests merged in 2024-08, with the labels that each got.

#1401 Added TopologySpreadConstraints to the backingstore pod for better performance
  pkg/backingstore/reconciler.go
  pkg/system/phase4_configuring.go
  pkg/util/util.go
Labels: size/M

#1399 disable automatic mount of SA token for pv-pool pod
  deploy/internal/pod-agent.yaml
  pkg/backingstore/reconciler.go
  pkg/bundle/deploy.go
Labels: size/XS

#1406 Added a fix to update bucketLogVolumes and bucketLogVolumeMounts in noobaa core pod
  pkg/system/phase2_creating.go
  pkg/system/reconciler.go
Labels: size/S

#1403 Adding node name env var to endpoints
  deploy/internal/deployment-endpoint.yaml
  pkg/bundle/deploy.go
Labels: size/S

#1407 Add NOOBAA_LOG_LEVEL to the agent pod
  deploy/internal/pod-agent.yaml
  pkg/backingstore/reconciler.go
  pkg/bundle/deploy.go
  pkg/controller/backingstore/backingstore_controller.go
Labels: size/M

#1408 Bump version to 5.18.0
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1409 backport into 5.17
  deploy/internal/deployment-endpoint.yaml
  deploy/internal/pod-agent.yaml
  pkg/backingstore/reconciler.go
  pkg/bundle/deploy.go
  pkg/controller/backingstore/backingstore_controller.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
  pkg/system/reconciler.go
  pkg/util/util.go
Labels: size/L

#1411 [Direct to 5.15] Handle empty initContainers array in postgres upgrade flow
  pkg/system/phase2_creating.go
Labels: size/XS

#1413 [Direct to 5.15] retrieve DB sts before verifying psql 15 upgrade
  pkg/system/reconciler.go
Labels: size/M

#1412 SCC fixes - new SCC for core
  deploy/internal/statefulset-core.yaml
  deploy/role_core.yaml
  deploy/scc_core.yaml
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
Labels: size/M

#1402 Fix provider env var panic
  deploy/internal/statefulset-core.yaml
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
Labels: size/S

#1414 Docs | STS | Update Docs
  doc/dev_guide/create_aws_role.sh
  doc/dev_guide/troubleshoot_sts_cluster.md
Labels: size/XS

#1416 Fixed 'Build Bundle' step in manaual-build workflow
  .github/workflows/manual-build.yml
Labels: size/S

#1405 Added support to join external noobaa system from hosted clusters
  pkg/noobaaaccount/reconciler.go
  pkg/system/phase1_verifying.go
  pkg/system/phase4_configuring.go
  pkg/util/util.go
Labels: size/L

#1417 Update GH actions
  .github/workflows/manual-build.yml
  .github/workflows/releaser.yaml
  .github/workflows/run_admission_test.yml
  .github/workflows/run_ci.yml
  .github/workflows/run_cosi_test.yaml
  .github/workflows/run_hac_test.yml
  .github/workflows/run_kms_azure_vault_test.yml
  .github/workflows/run_kms_dev_test.yml
  .github/workflows/run_kms_ibm_kp_test.yml
  .github/workflows/run_kms_kmip_test.yml
  .github/workflows/run_kms_rotate_test.yml
  .github/workflows/run_kms_tls_sa_test.yml
  .github/workflows/run_kms_tls_token_test.yml
  .github/workflows/testing.yml
Labels: size/M

#1410 noobaa/operator: Provide option to disable log colors
  deploy/internal/deployment-endpoint.yaml
  deploy/internal/pod-agent.yaml
  deploy/internal/statefulset-core.yaml
  pkg/backingstore/reconciler.go
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
Labels: size/M

#1420 Update to go 1.22, controller-runtime to v0.18.4 and rook api
  deploy/crds/noobaa.io_noobaas.yaml
  go.mod
  go.sum
  pkg/bundle/deploy.go
  pkg/controller/backingstore/backingstore_controller.go
  pkg/controller/bucketclass/bucketclass_controller.go
  pkg/controller/cephcluster/cephcluster_controller.go
  pkg/controller/ha/ha_controller.go
  pkg/controller/namespacestore/namespacestore_controller.go
  pkg/controller/noobaa/noobaa_controller.go
  pkg/controller/noobaaaccount/noobaaaccount_controller.go
  pkg/system/phase4_configuring.go
Labels: size/XL

#1421 [backport into 5.17] Backports into 5.17
  .github/workflows/manual-build.yml
  .github/workflows/releaser.yaml
  .github/workflows/run_admission_test.yml
  .github/workflows/run_ci.yml
  .github/workflows/run_cosi_test.yaml
  .github/workflows/run_hac_test.yml
  .github/workflows/run_kms_azure_vault_test.yml
  .github/workflows/run_kms_dev_test.yml
  .github/workflows/run_kms_ibm_kp_test.yml
  .github/workflows/run_kms_kmip_test.yml
  .github/workflows/run_kms_rotate_test.yml
  .github/workflows/run_kms_tls_sa_test.yml
  .github/workflows/run_kms_tls_token_test.yml
  .github/workflows/testing.yml
  deploy/crds/noobaa.io_noobaas.yaml
  deploy/internal/deployment-endpoint.yaml
  deploy/internal/pod-agent.yaml
  deploy/internal/statefulset-core.yaml
  deploy/role_core.yaml
  deploy/scc_core.yaml
  doc/dev_guide/create_aws_role.sh
  doc/dev_guide/troubleshoot_sts_cluster.md
  go.mod
  go.sum
  pkg/backingstore/reconciler.go
  pkg/bundle/deploy.go
  pkg/controller/backingstore/backingstore_controller.go
  pkg/controller/bucketclass/bucketclass_controller.go
  pkg/controller/cephcluster/cephcluster_controller.go
  pkg/controller/ha/ha_controller.go
  pkg/controller/namespacestore/namespacestore_controller.go
  pkg/controller/noobaa/noobaa_controller.go
  pkg/controller/noobaaaccount/noobaaaccount_controller.go
  pkg/noobaaaccount/reconciler.go
  pkg/system/phase1_verifying.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
  pkg/util/util.go
Labels: size/XL
