Repository noobaa/noobaa-operator, pull requests merged in 2024-06, with the labels that each got.

#1366 Nsfs : Default resources on hci odf
  deploy/crds/noobaa.io_noobaas.yaml
  deploy/internal/nsfs-pvc-cr.yaml
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
  pkg/system/reconciler.go
  pkg/util/util.go
Labels: size/L

#1376 [5.14] Bumping version from 5.14.8 to 5.14.9
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1373 Using PVC in place for storageclass provided by user for guaranteed logging
  deploy/crds/noobaa.io_noobaas.yaml
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/deploy.go
Labels: size/S

#1377 Bumped rook
  go.mod
  go.sum
Labels: size/M

#1378 Modify nsfs default pvc yaml file
  deploy/internal/nsfs-pvc-cr.yaml
  pkg/bundle/deploy.go
Labels: size/XS

#1379 [Backport | 5.14] SCC fixes
  deploy/internal/pod-agent.yaml
  deploy/internal/statefulset-postgres-db.yaml
  deploy/role.yaml
  deploy/scc.yaml
  deploy/scc_db.yaml
  deploy/scc_endpoint.yaml
  pkg/bundle/deploy.go
Labels: size/M

#1368 Validations for BucketLoggingPVC in case of guaranteed bucket logging
  pkg/system/phase1_verifying.go
  pkg/system/phase2_creating.go
  pkg/system/reconciler.go
Labels: size/L

#1380 [Direct to 5.15] Added error handling and retries in postgres upgrade scripts
  deploy/internal/configmap-postgres-initdb.yaml
  pkg/bundle/deploy.go
Labels: size/M

#1381 [Direct to 5.15] removed redundant code
  deploy/internal/configmap-postgres-initdb.yaml
  pkg/bundle/deploy.go
Labels: size/XS

#1371 Binding bucket logging pvc and path to core and endpoint pods
  deploy/internal/deployment-endpoint.yaml
  deploy/internal/statefulset-core.yaml
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
  pkg/system/reconciler.go
Labels: size/M
