Repository noobaa/noobaa-operator, pull requests merged in 2025-04, with the labels that each got.

#1481 nsfs - add mounted nsr name to env. DFBUGS-153
  pkg/system/phase4_configuring.go
Labels: size/XS

#1577 [5.16] Bumping version from 5.16.9 to 5.16.10
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1578 [5.15] Bumping version from 5.15.13 to 5.15.14
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1576 [5.17] Bumping version from 5.17.7 to 5.17.7
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1579 [5.14] Bumping version from 5.14.17 to 5.14.18
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1581 Handle low volume space for DB import
  deploy/crds/noobaa.io_noobaas.yaml
  deploy/role.yaml
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/bundle/deploy.go
  pkg/system/db_reconciler.go
  pkg/util/util.go
Labels: size/L

#1583 [Backport into 5.16] Bump jwt-go to avoid CVE
  go.mod
  go.sum
Labels: size/M

#1588 Added a flag DisableRoutes to manage openshift routes in noobaa
  deploy/crds/noobaa.io_noobaas.yaml
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/bundle/deploy.go
  pkg/options/options.go
  pkg/system/phase2_creating.go
  pkg/system/system.go
Labels: size/M

#1580 Block NSS creation when SignatureVersion v4 and endpoint non-secure
  pkg/cli/cli_suite_test.go
  pkg/cli/cli_test.go
  pkg/namespacestore/namespacestore.go
Labels: size/L

#1592 Webhook block NSS creation when SigVersion v4 and endpoint non-secure
  pkg/admission/test/unit/admission_unit_test.go
  pkg/validations/namespacestore_validations.go
Labels: size/M
