Repository noobaa/noobaa-operator, pull requests merged in 2025-03, with the labels that each got.

#1534 Fixing mount volume root keys - limit the secret size
  pkg/system/phase2_creating.go
  pkg/util/kms/kms_version.go
  pkg/util/kms/test/rotate/kms_rotate_test.go
  pkg/util/kms/test/rotate/kms_rotate_unit_test.go
Labels: size/L

#1546 [5.15] Bumping version from 5.15.11 to 5.15.13
  README.md
  pkg/bundle/deploy.go
  pkg/system/phase4_configuring.go
  version/version.go
Labels: size/S

#1547 [5.14] Bumping version from 5.14.15 to 5.14.17
  README.md
  pkg/bundle/deploy.go
  pkg/system/phase4_configuring.go
  version/version.go
Labels: size/S

#1544 [5.17] Upgrade golang.org/x/net to v0.33.0 to address CVE-2024-45338
  go.mod
  go.sum
Labels: size/S

#1549 [5.14] Upgrade golang.org/x/net to v0.33.0 to address CVE-2024-45338
  go.mod
  go.sum
Labels: size/S

#1551 Fixes for OLM deployments
  build/gen-odf-package.sh
  pkg/cnpg/cnpg.go
  pkg/olm/olm.go
Labels: size/M

#1552 gen_odf - quote with single quote
  build/gen-odf-package.sh
Labels: size/XS

#1553 Added CNPG webhooks definitions to CSV
  pkg/olm/olm.go
Labels: size/M

#1555 [5.18] Bumping version from 5.18.0 to 5.18.1
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1480 Bucket Notifications - docs
  doc/bucket-notifications.md
Labels: size/M

#1557 Update `golang.org/x/oauth2` to avoid CVE
  go.mod
  go.sum
Labels: size/XS

#1559 Add AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY to noobaa-account secret
  pkg/noobaaaccount/reconciler.go
Labels: size/XS

#1554 Added a fix to update bucket tagging when OBC labels are updated
  pkg/controller/obc/obc_controller.go
  pkg/obc/provisioner.go
  test/cli/test_cli_functions.sh
Labels: size/L

#1560 Noobaa HA - deploy HA postgres cluster using CNPG operator
  .github/workflows/run_admission_test.yml
  .github/workflows/run_cnpg_deployment_test.yml
  Makefile
  deploy/crds/noobaa.io_noobaas.yaml
  deploy/role.yaml
  go.mod
  go.sum
  pkg/apis/addtoscheme_noobaa_v1alpha1.go
  pkg/apis/noobaa/v1alpha1/cnpg_types.go
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/apis/noobaa/v1alpha1/register.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/deploy.go
  pkg/cnpg/cnpg.go
  pkg/install/install.go
  pkg/options/options.go
  pkg/system/db_reconciler.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
  pkg/system/reconciler.go
  pkg/system/system.go
  pkg/util/util.go
  test/cli/test_cli_functions.sh
  test/test-olm.sh
Labels: size/XXL

#1568 [5.18] Bumping version from 5.18.1 to 5.18.2
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1567 Bump deps (23/03/2025)
  go.mod
  go.sum
Labels: size/M

#1569 [Backport into 5.18] Backporting CVE fixes
  go.mod
  go.sum
  pkg/system/azure_utils.go
Labels: size/M

#1571 Implemented data import from the old DB to the cluster on upgrade
  go.mod
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/cnpg/cnpg.go
  pkg/install/install.go
  pkg/system/db_reconciler.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
  pkg/system/system.go
Labels: size/L

#1572 Cluster reconcile changes
  .github/workflows/run_cnpg_deployment_test.yml
  deploy/crds/noobaa.io_noobaas.yaml
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/deploy.go
  pkg/cnpg/cnpg.go
  pkg/install/install.go
  pkg/system/db_reconciler.go
  pkg/system/system.go
  pkg/util/util.go
Labels: size/L

#1573 Added cnpg-default-monitoring configmap to opeartor bundle
  pkg/olm/olm.go
Labels: size/XS
