Repository noobaa/noobaa-operator, pull requests merged in 2025-06, with the labels that each got.

#1626 [5.14] Bumping version from 5.14.18 to 5.14.19
  .github/workflows/cli-tests.yml
  .github/workflows/core-config-map-tests.yml
  .github/workflows/operator-olm-tests.yml
  .github/workflows/operator-tests.yml
  .github/workflows/run_admission_test.yml
  .github/workflows/run_ci.yml
  Makefile
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/L

#1629 Bumping version from 5.19.0 to 5.20.0
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1630 Add a cleanup option to our pre-upgrade dbdump
  deploy/internal/configmap-postgres-initdb.yaml
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
Labels: size/XS

#1638 [Backport into 5.16] Fix for quota always result 1PB quota limit
  pkg/bucket/bucket.go
  pkg/nb/types.go
  pkg/noobaaaccount/noobaaaccount.go
  pkg/noobaaaccount/reconciler.go
  pkg/util/util.go
Labels: size/L

#1641 [5.19 Backport] Support key rotation for KMIP KMS
  pkg/util/kms/kms_kmip.go
  pkg/util/kms/kms_kmip_storage.go
  pkg/util/kms/kms_version.go
  pkg/util/kms/test/kmip/kms_kmip_test.go
Labels: size/L
