Repository noobaa/noobaa-operator, pull requests merged in 2025-08, with the labels that each got.

#1670 CI | Upgrade tests | workflow fixes
  .github/workflows/manual-upgrade-tests.yaml
  Makefile
Labels: size/XS

#1671 Fix noobaa-core routes permission issue
  deploy/role_core.yaml
  pkg/bundle/deploy.go
Labels: size/S

#1658 Added monthly scheduling and automation of container image tag
  .github/workflows/update-noobaa-core-tag.yml
Labels: size/M

#1677 Change the kubecheck of standaloneDBPod to be quiet
  pkg/system/db_reconciler.go
Labels: size/XS

#1682 5.20 rebase
  .github/workflows/update-noobaa-core-tag.yml
  deploy/internal/prometheus-rules.yaml
  pkg/bundle/deploy.go
  pkg/system/db_reconciler.go
Labels: size/L

#1685 [Backport into 5.19] Update AWS Regions with ap-east-2
  README.md
  pkg/bundle/deploy.go
  pkg/util/util.go
  version/version.go
Labels: size/S

#1674 [Direct to 5.19] Check if Spec.Affinity is changed in wasClusterSpecChanged
  pkg/system/db_reconciler.go
Labels: size/XS

#1686 Changed the version variable to be var
  version/version.go
Labels: size/XS
