Repository noobaa/noobaa-operator, pull requests merged in 2025-02, with the labels that each got.

#1520 bucket notifications - need connect files also in endpoint for put bucket notif
  pkg/system/phase4_configuring.go
Labels: size/S

#1524 [5.17] Bumping version from 5.17.2 to 5.17.4
  Makefile
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1517 [5.16] Bumping version from 5.16.6 to 5.16.7
  .github/workflows/manual-build.yml
  .github/workflows/releaser.yaml
  .github/workflows/run_admission_test.yml
  .github/workflows/run_ci.yml
  .github/workflows/run_cosi_test.yaml
  .github/workflows/run_hac_test.yml
  .github/workflows/run_kms_azure_vault_test.yml
  .github/workflows/run_kms_dev_test.yml
  .github/workflows/run_kms_ibm_kp_test.yml
  .github/workflows/run_kms_kmip_test.yml
  .github/workflows/run_kms_rotate_test.yml
  .github/workflows/run_kms_tls_sa_test.yml
  .github/workflows/run_kms_tls_token_test.yml
  .github/workflows/testing.yml
  Makefile
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/M

#1518 [5.15] Bumping version from 5.15.10 to 5.15.11
  .github/workflows/releaser.yaml
  .github/workflows/run_admission_test.yml
  .github/workflows/run_cosi_test.yaml
  Makefile
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1525 Bump rook
  go.mod
  go.sum
  pkg/system/azure_utils.go
Labels: size/L

#1526 Bump go to 1.23 and dependencies according to ocs-operator
  .github/workflows/golangci-lint.yml
  .github/workflows/manual-build.yml
  .github/workflows/run_admission_test.yml
  .github/workflows/run_ci.yml
  .github/workflows/run_cosi_test.yaml
  .github/workflows/run_hac_test.yml
  .github/workflows/run_kms_azure_vault_test.yml
  .github/workflows/run_kms_dev_test.yml
  .github/workflows/run_kms_ibm_kp_test.yml
  .github/workflows/run_kms_kmip_test.yml
  .github/workflows/run_kms_rotate_test.yml
  .github/workflows/run_kms_tls_sa_test.yml
  .github/workflows/run_kms_tls_token_test.yml
  .github/workflows/testing.yml
  go.mod
  go.sum
Labels: size/L

#1527 Update AWS Regions with New Region
  pkg/util/util.go
Labels: size/XS

#1529 fixed lint error
  pkg/system/phase4_configuring.go
Labels: size/XS

#1530 [5.17] Bumping version from 5.17.4 to 5.17.5
  README.md
  pkg/bundle/deploy.go
  pkg/system/phase4_configuring.go
  version/version.go
Labels: size/S

#1528 Add CLI commands for cloudnativepg installation
  go.mod
  go.sum
  pkg/cli/cli.go
  pkg/cnpg/cnpg.go
  pkg/install/install.go
  pkg/options/options.go
Labels: size/XL

#1531 [Backport into 5.18] fixed lint error
  pkg/system/phase4_configuring.go
Labels: size/XS

#1532 Integrated Cloudnative-pg into OLM package
  Makefile
  build/gen-odf-package.sh
  pkg/cnpg/cnpg.go
  pkg/olm/olm.go
Labels: size/XL

#1535 temporarily remove cnpg image from gen-odf-package.sh
  build/gen-odf-package.sh
Labels: size/XS

#1537 [5.17] Bumping version from 5.17.5 to 5.17.6
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1538 CNPG fixes for ODF build
  build/gen-odf-package.sh
  pkg/cnpg/cnpg.go
  pkg/olm/olm.go
Labels: size/S

#1539 Add workflow to build custom CNPG operator image
  .github/workflows/build-cnpg.yml
  .github/workflows/manual-build.yml
Labels: size/M

#1540 fix to gen-odf-package.sh
  build/gen-odf-package.sh
Labels: size/XS

#1541 [Backport into 5.17] Bug fixes for parsed AWS region and quota always result 1PB quota limit
  deploy/cluster_role.yaml
  pkg/bucket/bucket.go
  pkg/bundle/deploy.go
  pkg/util/util.go
Labels: size/L

#1543 [Backport into 5.16] Fix for region fetch from GetAWSRegion()
  deploy/cluster_role.yaml
  pkg/bundle/deploy.go
  pkg/util/util.go
Labels: size/M
