Repository noobaa/noobaa-operator, pull requests merged in 2025-01, with the labels that each got.

#1477 [azure] updated storage version.
  pkg/system/azure_utils.go
Labels: size/XS

#1501 Bump rook to v0.0.0-20250103143133-54c2ba5071bc and go directive to go 1.23
  .github/workflows/golangci-lint.yml
  .github/workflows/manual-build.yml
  .github/workflows/run_admission_test.yml
  .github/workflows/run_ci.yml
  .github/workflows/run_cosi_test.yaml
  .github/workflows/run_hac_test.yml
  .github/workflows/run_kms_azure_vault_test.yml
  .github/workflows/run_kms_dev_test.yml
  .github/workflows/run_kms_ibm_kp_test.yml
  .github/workflows/run_kms_kmip_test.yml
  .github/workflows/run_kms_rotate_test.yml
  .github/workflows/run_kms_tls_sa_test.yml
  .github/workflows/run_kms_tls_token_test.yml
  .github/workflows/testing.yml
  go.mod
  go.sum
Labels: size/L

#1503 [5.18] CVE-2024-45338 | Bump golang.org/x/net to v0.33.0
  go.mod
  go.sum
Labels: size/M

#1489 Noobaa/Backingstore : Need facility to change labels
  pkg/backingstore/reconciler.go
Labels: size/S

#1506 [5.17] Bumping version from 5.17.1 to 5.17.2
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1507 [5.15] Bumping version from 5.15.9 to 5.15.10
  .github/workflows/golangci-lint.yml
  .golangci.yml
  Makefile
  README.md
  pkg/backingstore/backingstore.go
  pkg/bucketclass/bucketclass.go
  pkg/bundle/deploy.go
  pkg/cosi/provisioner.go
  pkg/install/install.go
  pkg/namespacestore/namespacestore.go
  pkg/nb/rpc_ws.go
  pkg/noobaaaccount/noobaaaccount.go
  pkg/obc/obc.go
  pkg/obc/provisioner.go
  pkg/system/reconciler.go
  pkg/util/kms/test/dev/kms_dev_test.go
  pkg/util/kms/test/ibm-kp/kms_ibm_kp_test.go
  version/version.go
Labels: size/L

#1504 [5.16] Bumping version from 5.16.5 to 5.16.6
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1508 Move docs to the core repo
  README.md
  doc/bucket-replication.md
  doc/bucket-types.md
  doc/s3-compatibility.md
Labels: size/L

#1511 Also install setuptools
  Makefile
Labels: size/XS

#1514 bucket notifications - connect mount should be unique
  pkg/system/phase2_creating.go
Labels: size/XS

#1513 Bump version to 5.19.0
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S
