Repository noobaa/noobaa-operator, pull requests merged in 2025-05, with the labels that each got.

#1596 Support key rotation to Azure vault
  pkg/util/kms/kms_azure.go
  pkg/util/kms/test/azure-vault/kms_azure_vault_test.go
Labels: size/M

#1599 postgres setup enhancements
  deploy/internal/configmap-postgres-db.yaml
  deploy/internal/statefulset-postgres-db.yaml
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
Labels: size/M

#1601 [Backport to 5.16] postgres setup enhancements
  deploy/internal/configmap-postgres-db.yaml
  deploy/internal/statefulset-postgres-db.yaml
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
Labels: size/S

#1600 [Backport to 5.17] postgres setup enhancements
  deploy/internal/configmap-postgres-db.yaml
  deploy/internal/statefulset-postgres-db.yaml
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
Labels: size/S

#1602 [Backport to 5.15] postgres setup enhancements
  deploy/internal/configmap-postgres-db.yaml
  deploy/internal/statefulset-postgres-db.yaml
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
Labels: size/S

#1603 [Backport to 5.14] postgres setup enhancements
  deploy/internal/configmap-postgres-db.yaml
  deploy/internal/statefulset-postgres-db.yaml
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
Labels: size/M

#1605 [5.19 Backport] Support key rotation to Azure vault
  pkg/util/kms/kms_azure.go
  pkg/util/kms/test/azure-vault/kms_azure_vault_test.go
Labels: size/M

#1597 Update run_admission_test.yml to use native github action minikube
  .github/workflows/run_admission_test.yml
Labels: size/M

#1595 [5.18] Bumping version from 5.18.2 to 5.18.3
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1606 [Backport into 5.19] updating x/net and tests
  .github/workflows/run_admission_test.yml
  go.mod
  go.sum
Labels: size/M

#1598 Enable DB pods monitoring by default
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/system/db_reconciler.go
Labels: size/S

#1610 CI | refactor the tests
  .github/workflows/cli-tests.yml
  .github/workflows/core-config-map-tests.yml
  .github/workflows/operator-olm-tests.yml
  .github/workflows/operator-tests.yml
  .github/workflows/run_ci.yml
  Makefile
Labels: size/L

#1609 [5.18] Bumping version from 5.18.3 to 5.18.4
  .github/workflows/cli-tests.yml
  .github/workflows/core-config-map-tests.yml
  .github/workflows/operator-olm-tests.yml
  .github/workflows/operator-tests.yml
  .github/workflows/run_admission_test.yml
  .github/workflows/run_ci.yml
  Makefile
  README.md
  go.mod
  go.sum
  pkg/bundle/deploy.go
  version/version.go
Labels: size/L

#1611 [Backport into 5.19] - Backporting into 5.19
  .github/workflows/cli-tests.yml
  .github/workflows/core-config-map-tests.yml
  .github/workflows/operator-olm-tests.yml
  .github/workflows/operator-tests.yml
  .github/workflows/run_ci.yml
  Makefile
  pkg/apis/noobaa/v1alpha1/noobaa_types.go
  pkg/system/db_reconciler.go
Labels: size/L

#1612 Update setup-minikube from v0.0.14 to v0.0.19 and kubernetes-version to v1.33.0
  .github/workflows/cli-tests.yml
  .github/workflows/core-config-map-tests.yml
  .github/workflows/run_admission_test.yml
Labels: size/S

#1613 Passing postgres secret as a vol mount instead of env
  deploy/internal/deployment-endpoint.yaml
  deploy/internal/statefulset-core.yaml
  pkg/bundle/deploy.go
  pkg/options/options.go
  pkg/system/db_reconciler.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
Labels: size/L

#1616 [5.17] Bumping version from 5.17.7 to 5.17.8
  .github/workflows/cli-tests.yml
  .github/workflows/core-config-map-tests.yml
  .github/workflows/operator-olm-tests.yml
  .github/workflows/operator-tests.yml
  .github/workflows/run_admission_test.yml
  .github/workflows/run_ci.yml
  Makefile
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/L

#1608 [Review only] Save DB diagnostics for CLBO debugging
  deploy/internal/Dockerfile.postgres
  deploy/internal/scripts/db-crash-collector.sh
  deploy/internal/scripts/run-postgresql-wrapper.sh
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
Labels: size/L

#1617 Minor fixes
  deploy/internal/scripts/db-crash-collector.sh
  pkg/bundle/deploy.go
Labels: size/XS
