Repository noobaa/noobaa-operator, pull requests merged in 2025-07, with the labels that each got.

#1607 Authentication for metrics and version endpoint
  deploy/internal/deployment-endpoint.yaml
  deploy/internal/statefulset-core.yaml
  pkg/bundle/deploy.go
  pkg/system/phase2_creating.go
  pkg/system/phase4_configuring.go
  pkg/system/reconciler.go
Labels: size/L

#1643 Improve upgrade handling to sync pods restarts
  deploy/internal/statefulset-core.yaml
  pkg/bundle/deploy.go
  pkg/system/db_reconciler.go
  pkg/system/phase2_creating.go
  pkg/system/phase3_connecting.go
  pkg/system/reconciler.go
Labels: size/L

#1648 Update AWS Regions with ap-east-2
  pkg/util/util.go
Labels: size/XS

#1647 [5.14] Bumping version from 5.14.19 to 5.14.20
  .github/workflows/core-config-map-tests.yml
  pkg/bundle/deploy.go
  version/version.go
Labels: size/M

#1639 csv: add cpu, memory requests value for operator
  deploy/operator.yaml
  pkg/bundle/deploy.go
Labels: size/XS

#1650 [Backport to 5.19] Fixing KMIP issues
  pkg/util/kms/kms_kmip.go
  pkg/util/kms/kms_kmip_storage.go
  pkg/util/kms/kms_version.go
Labels: size/M

#1654 KMIP Upgrade - Fix for empty StringData after calling KubeUpdate
  pkg/util/kms/kms_kmip_storage.go
Labels: size/XS

#1661 [5.19] Bumping version from 5.19.0 to 5.19.1
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S

#1668 [5.14] Bumping version from 5.14.20 to 5.14.21
  README.md
  pkg/bundle/deploy.go
  version/version.go
Labels: size/S
